"""
Public-safe MCP server: Linnworks API lookup only. No macro conventions, no golden
examples, no internal standards - just "what endpoint/model do I need." Its four
lookup tools are shared implementation with mcp-server/server.py (the full internal
server) via mcp-shared/ - see that package's docstring for why sharing was judged
safe (both servers are internal-only in practice; nothing macro/golden-example-
related lives in the shared code regardless). This file still can't see or expose
anything about how this team writes macros - that's still mcp-server-only.

Read-only - never calls the real Linnworks API, only reads local markdown under
references/api/ generated by scripts/sync_api_spec.py.

Run locally (stdio, for an IDE/AI client):
    python server.py

Run as a network service (for hosting - see README.md):
    python server.py --http --host 0.0.0.0 --port 8787
"""

import argparse
import pathlib
import sys
from typing import Optional

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent / "mcp-shared"))
import reference_tools  # noqa: E402
from transport import add_http_args, configure_transport_security  # noqa: E402

from mcp.server.fastmcp import FastMCP

mcp = FastMCP(
    "linnworks-api",
    instructions=(
        "Linnworks API endpoint/model lookup. Prefer these tools over general "
        "knowledge for anything about Linnworks endpoints, request/response models, "
        "or rate limits - this reflects Linnworks' own published API specs, not "
        "general training data which may be stale or wrong."
    ),
)


@mcp.tool()
def list_controllers(status: Optional[str] = None) -> str:
    """List every Linnworks API controller, with its API version and how current
    it is (done/generated/in-review/todo). Optionally filter by status. Use this
    to discover what's available before calling get_endpoint."""
    return reference_tools.list_controllers_impl(status, include_notes=False)


mcp.tool()(reference_tools.get_endpoint)
mcp.tool()(reference_tools.search_api)
mcp.tool()(reference_tools.get_model)


def main():
    parser = argparse.ArgumentParser()
    add_http_args(parser, default_port=8787)
    args = parser.parse_args()

    if args.http:
        mcp.settings.host = args.host
        mcp.settings.port = args.port
        configure_transport_security(mcp, args.allowed_host)
        mcp.run(transport="streamable-http")
    else:
        mcp.run(transport="stdio")


if __name__ == "__main__":
    main()
