"""
Public-safe MCP server: Linnworks API lookup only. No macro conventions, no golden
examples, no internal standards - just "what endpoint/model do I need." This is
deliberately a separate, standalone script from mcp-server/server.py (the full
internal server) so it can be shared or hosted publicly without exposing anything
about how this team writes macros.

Read-only - never calls the real Linnworks API, only reads local markdown under
references/api/ generated by scripts/sync_api_spec.py.

Run locally (stdio, for an IDE/AI client):
    python server.py

Run as a network service (for hosting - see README.md):
    python server.py --http --host 0.0.0.0 --port 8787
"""

import argparse
import re
import pathlib
from typing import Optional

from mcp.server.fastmcp import FastMCP

PLATFORM_ROOT = pathlib.Path(__file__).resolve().parent.parent
API_DIR = PLATFORM_ROOT / "references" / "api"
STATUS_FILE = PLATFORM_ROOT / "migration" / "STATUS.md"

mcp = FastMCP(
    "linnworks-api",
    instructions=(
        "Linnworks API endpoint/model lookup. Prefer these tools over general "
        "knowledge for anything about Linnworks endpoints, request/response models, "
        "or rate limits - this reflects Linnworks' own published API specs, not "
        "general training data which may be stale or wrong."
    ),
)


def _read(path: pathlib.Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def _find_controller_file(controller: str, version: str) -> Optional[pathlib.Path]:
    version_dir = API_DIR / version
    if not version_dir.exists():
        return None
    for f in version_dir.glob("*.md"):
        if f.stem.lower() == controller.lower():
            return f
    return None


@mcp.tool()
def list_controllers(status: Optional[str] = None) -> str:
    """List every Linnworks API controller, with its API version and how current
    it is (done/generated/in-review/todo). Optionally filter by status. Use this
    to discover what's available before calling get_endpoint."""
    if not STATUS_FILE.exists():
        return "Controller list unavailable."
    rows = []
    for line in _read(STATUS_FILE).splitlines():
        if not line.startswith("|") or line.startswith("|---") or line.startswith("| Controller"):
            continue
        cols = [c.strip() for c in line.strip("|").split("|")]
        if len(cols) != 6:
            continue
        controller, _spec_version, api_version, _last_synced, row_status, _notes = cols
        if status and row_status.lower() != status.lower():
            continue
        rows.append(f"{controller} ({api_version}) - {row_status}")
    return "\n".join(rows) if rows else f"No controllers found with status={status!r}."


@mcp.tool()
def get_endpoint(controller: str, version: str = "v1") -> str:
    """Get the full endpoint reference for one controller: every HTTP method/path,
    rate limits, parameters, and referenced models. version is "v1" or "v2".
    Controller name is case-insensitive."""
    f = _find_controller_file(controller, version)
    if not f:
        available = sorted(p.stem for p in (API_DIR / version).glob("*.md")) if (API_DIR / version).exists() else []
        return f'No {version} controller named "{controller}". Available: {", ".join(available)}'
    return _read(f)


@mcp.tool()
def search_api(query: str, version: Optional[str] = None, max_results: int = 15) -> str:
    """Full-text search across every controller's endpoint reference (v1 and v2
    unless version is specified). Matches endpoint paths, method names, model
    names, and descriptions. Use this when you don't know which controller an
    endpoint lives in - e.g. search_api("fulfillment status")."""
    versions = [version] if version else ["v1", "v2"]
    pattern = re.compile(re.escape(query), re.IGNORECASE)
    results = []
    for v in versions:
        vdir = API_DIR / v
        if not vdir.exists():
            continue
        for f in sorted(vdir.glob("*.md")):
            for i, line in enumerate(_read(f).splitlines(), start=1):
                if pattern.search(line):
                    results.append(f"{f.stem} ({v}):{i}: {line.strip()}")
                    if len(results) >= max_results:
                        break
            if len(results) >= max_results:
                break
        if len(results) >= max_results:
            break
    if not results:
        return f'No matches for "{query}".'
    return "\n".join(results)


@mcp.tool()
def get_model(name: str, version: Optional[str] = None) -> str:
    """Get one model/schema's field table by name (e.g. "StockLocation",
    "GetOrdersResponse"). Searches every controller's docs since a model can be
    referenced from more than one; returns every match if the same name appears
    in multiple controllers."""
    versions = [version] if version else ["v1", "v2"]
    heading_re = re.compile(r"^### `?" + re.escape(name) + r"`?\s*$")
    matches = []
    for v in versions:
        vdir = API_DIR / v
        if not vdir.exists():
            continue
        for f in sorted(vdir.glob("*.md")):
            lines = _read(f).splitlines()
            for i, line in enumerate(lines):
                if heading_re.match(line.strip()):
                    section = [line]
                    for j in range(i + 1, len(lines)):
                        if lines[j].startswith("## ") or lines[j].startswith("### "):
                            break
                        section.append(lines[j])
                    matches.append(f"--- from {f.stem} ({v}) ---\n" + "\n".join(section).strip())
    if not matches:
        return f'No model named "{name}" found.'
    return "\n\n".join(matches)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--http", action="store_true", help="Run as a network service (streamable-http) instead of stdio")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8787)
    args = parser.parse_args()

    if args.http:
        mcp.settings.host = args.host
        mcp.settings.port = args.port
        mcp.run(transport="streamable-http")
    else:
        mcp.run(transport="stdio")


if __name__ == "__main__":
    main()
