"""
MCP server exposing everything under references/ and migration/STATUS.md so any
MCP-compatible AI (Claude, Cursor, Antigravity, VS Code Copilot, etc.) can query
the Linnworks platform's knowledge base directly instead of having it pasted into a
system prompt. Read-only - this server never calls the real Linnworks API, it only
reads local markdown/docs generated by the scripts/ pipeline.

This is the FULL internal server - includes macro conventions, golden-example
macros, and standards linting, unlike mcp-server-api/ (the public-safe subset).
Hosting this one publicly means anyone with the URL can read your golden-example
macros and internal conventions - that's a deliberate choice, not an accident;
see README.md.

Run locally (stdio, for an IDE/AI client on this machine):
    python server.py

Run as a network service (for hosting - see README.md):
    python server.py --http --host 0.0.0.0 --port 8788

Claude Desktop config (claude_desktop_config.json), local stdio form:
    {
      "mcpServers": {
        "linnworks-platform": {
          "command": "python",
          "args": ["C:\\path\\to\\linnworks-platform\\mcp-server\\server.py"]
        }
      }
    }
"""

import argparse
import re
import pathlib
import shutil
import subprocess
import sys
import threading
from typing import Optional

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent / "mcp-shared"))
import reference_tools  # noqa: E402
from transport import add_http_args, configure_transport_security  # noqa: E402

from mcp.server.fastmcp import FastMCP

PLATFORM_ROOT = pathlib.Path(__file__).resolve().parent.parent
API_DIR = PLATFORM_ROOT / "references" / "api"
MACRO_DIR = PLATFORM_ROOT / "references" / "macro"
STANDARDS_DIR = PLATFORM_ROOT / "references" / "standards"
STATUS_FILE = PLATFORM_ROOT / "migration" / "STATUS.md"
_read = reference_tools.read_text
_find_by_stem = reference_tools.find_by_stem
COMPILE_CHECK_DIR = pathlib.Path(__file__).resolve().parent / "compile_check"
COMPILE_CHECK_PROJ = COMPILE_CHECK_DIR / "CompileCheck.csproj"
COMPILE_CHECK_SRC = COMPILE_CHECK_DIR / "Macro.cs"
_COMPILE_ERROR_RE = re.compile(r"Macro\.cs\((\d+),(\d+)\):\s+error\s+(CS\d+):\s+(.+?)\s+\[")
_compile_lock = threading.Lock()

mcp = FastMCP(
    "linnworks-platform",
    instructions=(
        "Reference layer for the Linnworks API and macro helpers. Prefer these tools "
        "over general knowledge for anything about Linnworks endpoints, models, rate "
        "limits, or macro FTP/SFTP/Email/Dropbox integration patterns - the underlying "
        "SDK (LinnworksAPI/) and this reference set are kept in sync with Linnworks' "
        "own published specs, general knowledge is not."
    ),
)


@mcp.tool()
def list_controllers(status: Optional[str] = None) -> str:
    """List every Linnworks API controller tracked in migration/STATUS.md, with its
    API version and migration status. Optionally filter by status
    (done / generated / in-review / todo). Use this to discover what's available
    before calling get_endpoint."""
    return reference_tools.list_controllers_impl(status, include_notes=True)


mcp.tool()(reference_tools.get_endpoint)
mcp.tool()(reference_tools.search_api)
mcp.tool()(reference_tools.get_model)


@mcp.tool()
def get_macro_calling_guide() -> str:
    """Get the calling-convention guide for reaching LinnworksAPI from a macro:
    the difference between running inside Linnworks' own macro engine
    (LinnworksMacroBase, pre-authenticated Api property) versus standalone code
    (manual AuthorizeByApplication + ApiObjectManager), session lifetime, and how
    errors surface. Read this before writing macro code that calls the SDK - it's
    thin by design and doesn't duplicate endpoint docs (use search_api/get_endpoint
    for those)."""
    f = MACRO_DIR / "linnworks-api" / "overview.md"
    if not f.exists():
        return "references/macro/linnworks-api/overview.md not found."
    return _read(f)


@mcp.tool()
def get_macro_integration(category: str) -> str:
    """Get macro integration reference for FTP/SFTP/Email/Dropbox/raw-HTTP: the
    IProxyHelper contract, request/response types, and real working call-site code
    from LinnMacroCustomer. category is one of: ftp, ftps, sftp, email, dropbox, web."""
    f = _find_by_stem(MACRO_DIR / "integrations", category)
    if not f:
        available = sorted(p.stem for p in (MACRO_DIR / "integrations").glob("*.md"))
        return f'No macro integration named "{category}". Available: {", ".join(available)}'
    return _read(f)


@mcp.tool()
def list_macro_patterns() -> str:
    """List hand-written macro pattern docs (references/macro/patterns/) - things a
    developer figured out that aren't derivable from code or the API spec alone
    (gotchas, non-obvious sequencing, workarounds). Call get_macro_pattern to read one."""
    patterns_dir = MACRO_DIR / "patterns"
    names = sorted(p.stem for p in patterns_dir.glob("*.md") if p.stem != "_template")
    if not names:
        return "No macro patterns written yet."
    return "\n".join(names)


@mcp.tool()
def get_macro_pattern(name: str) -> str:
    """Read one hand-written macro pattern doc by name (see list_macro_patterns)."""
    f = _find_by_stem(MACRO_DIR / "patterns", name)
    if not f:
        return f'No macro pattern named "{name}". Call list_macro_patterns for available names.'
    return _read(f)


@mcp.tool()
def get_standards() -> str:
    """Get the coding conventions macros/plugins generated against this platform
    should follow (naming, error handling, logging)."""
    f = STANDARDS_DIR / "conventions.md"
    if not f.exists():
        return "references/standards/conventions.md not found."
    return _read(f)


@mcp.tool()
def get_macro_conventions() -> str:
    """Get macro-authoring conventions derived from real approved macros: mandatory
    structure, start/end logging, human-readable IDs only in logs (never raw GUIDs),
    the required rate-limit-safe API-calling pattern (proactive pacing + exponential
    backoff on HTTP 429 - with a ready-to-use code template), server-side filter/
    endpoint selection guidance, and idempotency requirements for mutating macros.
    Read this before writing or reviewing any macro. See also list_golden_examples/
    get_golden_example for the real macros these rules were derived from."""
    f = STANDARDS_DIR / "macro_conventions.md"
    if not f.exists():
        return "references/standards/macro_conventions.md not found."
    return _read(f)


@mcp.tool()
def list_golden_examples() -> str:
    """List real, approved macros kept as reference examples, with a one-line
    summary of what each demonstrates. Call get_golden_example to read one, or read
    references/standards/golden_examples/README.md (via get_golden_example_notes)
    for the full annotated breakdown of what to copy and what to fix in each."""
    examples_dir = STANDARDS_DIR / "golden_examples"
    files = sorted(examples_dir.glob("*.cs"))
    if not files:
        return "No golden example macros yet."
    return "\n".join(f.stem for f in files)


@mcp.tool()
def get_golden_example(name: str) -> str:
    """Read one golden example macro's full source by name (see list_golden_examples).
    These are real approved macros - not all of them are fully compliant with
    get_macro_conventions()'s rules; call get_golden_example_notes for what to copy
    vs fix in each before using one as a template."""
    examples_dir = STANDARDS_DIR / "golden_examples"
    matches = [f for f in examples_dir.glob("*.cs") if f.stem == name or f.stem.lower() == name.lower()]
    if not matches:
        available = sorted(f.stem for f in examples_dir.glob("*.cs"))
        return f'No golden example named "{name}". Available: {", ".join(available)}'
    return _read(matches[0])


@mcp.tool()
def get_golden_example_notes() -> str:
    """Get the annotated breakdown of every golden example macro: what each one
    demonstrates well (copy this) and where it violates get_macro_conventions()'s
    rules (fix this if reusing). Read this before using any golden example as a
    template - none of them are perfect."""
    f = STANDARDS_DIR / "golden_examples" / "README.md"
    if not f.exists():
        return "references/standards/golden_examples/README.md not found."
    return _read(f)


_GOLDEN_EXAMPLE_SECTION_RE = re.compile(r"(?m)^## (.+\.cs)\s*$")


@mcp.tool()
def search_golden_examples(query: str, max_results: int = 5) -> str:
    """Find the closest existing golden example macro to a new requirement, without
    already knowing its filename. Searches the full annotated write-up of every
    golden example (golden_examples/README.md - what it demonstrates, what to copy,
    what to fix), not just the filename, so e.g. search_golden_examples("rate
    limit"), search_golden_examples("idempotency"), or search_golden_examples("folder
    sync") all find the relevant example even if you don't know its name. Ranked by
    match count in each example's section. Call get_golden_example(name) to read the
    full source of whichever one comes back, or get_golden_example_notes() to read
    every example's write-up at once instead of searching."""
    f = STANDARDS_DIR / "golden_examples" / "README.md"
    if not f.exists():
        return "references/standards/golden_examples/README.md not found."
    text = _read(f)
    pieces = _GOLDEN_EXAMPLE_SECTION_RE.split(text)
    # pieces[0] is the preamble before the first "## X.cs" heading; then it
    # alternates heading, body, heading, body, ...
    entries = [(pieces[i], pieces[i + 1]) for i in range(1, len(pieces) - 1, 2)]

    # Word-level, substring-within-word matching - not a literal phrase search.
    # "rate limit" needs to match text that says "rate-limit" (hyphen, not space)
    # and "folder sync" needs to match "Syncs order folders" (plural/tense
    # mismatch) - both failed under plain substring matching during testing.
    query_words = re.findall(r"[a-z0-9]+", query.lower())
    if not query_words:
        return 'Empty query - pass at least one word, e.g. search_golden_examples("rate limit").'

    def _word_matches(query_word: str, doc_word: str) -> bool:
        # Prefix relation, not "contains anywhere" - the latter false-positived on
        # short common words (e.g. "is") being trivially a substring of an unrelated
        # query word (e.g. "nonexistent" contains "is") during testing. Require
        # length >= 3 before allowing a prefix match at all, so single/double-letter
        # doc words can never drive a match.
        if query_word == doc_word:
            return True
        if len(query_word) < 3 or len(doc_word) < 3:
            return False
        return doc_word.startswith(query_word) or query_word.startswith(doc_word)

    def _word_hits(section_text: str) -> int:
        doc_words = re.findall(r"[a-z0-9]+", section_text.lower())
        return sum(1 for qw in query_words if any(_word_matches(qw, dw) for dw in doc_words))

    scored = []
    for heading, body in entries:
        heading_hits = _word_hits(heading)
        body_hits = _word_hits(body)
        score = heading_hits * 3 + body_hits
        if score > 0:
            scored.append((score, heading, body.strip()))
    if not scored:
        return (
            f'No golden example matches "{query}". Call list_golden_examples() to see '
            f"all of them, or get_golden_example_notes() to read every write-up."
        )
    scored.sort(key=lambda item: -item[0])

    results = []
    for score, heading, body in scored[:max_results]:
        snippet = body if len(body) <= 600 else body[:600].rstrip() + "..."
        results.append(f"--- {heading} (match score {score}) ---\n{snippet}")
    return "\n\n".join(results)


_MACRO_NAME_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

# Rate-limit wrapper is macro_conventions.md rule 4's exact reference pattern
# (ExecuteApi/PaceApiCall from 02_ContainerEtaFolderSync.cs) - copied verbatim, not
# reworded, so scaffold_macro's output matches what get_macro_conventions() documents
# as mandatory rather than a paraphrase that could drift from it over time.
_RATE_LIMIT_HELPERS = '''\
        private static readonly object RateLimitLock = new();
        private static DateTime _lastApiCallUtc = DateTime.MinValue;
        private const int MinimumApiSpacingMilliseconds = 550;

        private static void PaceApiCall()
        {
            lock (RateLimitLock)
            {
                var elapsed = (DateTime.UtcNow - _lastApiCallUtc).TotalMilliseconds;
                if (elapsed < MinimumApiSpacingMilliseconds)
                    Thread.Sleep(MinimumApiSpacingMilliseconds - (int)elapsed);
                _lastApiCallUtc = DateTime.UtcNow;
            }
        }

        private T ExecuteApi<T>(string operationName, Func<T> operation)
        {
            const int maxAttempts = 5;
            var retryDelaysSeconds = new[] { 5, 15, 30, 60 };
            for (var attempt = 1; attempt <= maxAttempts; attempt++)
            {
                PaceApiCall();
                try { return operation(); }
                catch (Exception ex) when (IsHttp429(ex) && attempt < maxAttempts)
                {
                    Thread.Sleep(TimeSpan.FromSeconds(retryDelaysSeconds[attempt - 1]));
                }
            }
            throw new InvalidOperationException($"{operationName} failed without returning a result.");
        }

        private static bool IsHttp429(Exception exception)
        {
            for (var current = exception; current != null; current = current.InnerException)
            {
                if (current is WebException webEx && webEx.Response is HttpWebResponse http && (int)http.StatusCode == 429)
                    return true;
                if (current.Message.Contains("error 429", StringComparison.OrdinalIgnoreCase) ||
                    current.Message.Contains("Too Many Requests", StringComparison.OrdinalIgnoreCase))
                    return true;
            }
            return false;
        }
'''

# Rule shape mirrors rule_macro.md's own example: Guid[] OrderIds first param,
# per-order try/catch delegated to a helper (one bad order can't stop the batch),
# distinct-order loop. ExecuteApi wraps the one real Api.* call already present.
# Every parameter (OrderIds included) gets an XML <param> doc comment - Linnworks'
# macro settings UI surfaces these to whoever configures the macro (the pattern
# 03_PickListMonitoring.cs already uses for its Execute params), so a parameter
# with no description is a real usability gap, not a cosmetic one.
_RULE_TEMPLATE = '''\
using System;
using System.Linq;
using System.Net;
using System.Threading;
using LinnworksMacroHelpers;

namespace __MACRO_NAME__
{
    public class __MACRO_NAME__ : LinnworksMacroBase
    {
        /// <summary>
        /// Rule-triggered entry point.
        /// </summary>
__PARAMS_DOC__
        public void Execute(__PARAMS_DECL__)
        {
            Logger.WriteInfo("__MACRO_NAME__ started.");

            try
            {
                if (OrderIds == null || OrderIds.Length == 0)
                {
                    Logger.WriteInfo("No OrderIds supplied. Macro exiting.");
                    return;
                }

                foreach (var orderId in OrderIds.Distinct())
                {
                    ProcessOrder(orderId);
                }
            }
            catch (Exception ex)
            {
                Logger.WriteError($"Unhandled macro error: {ex.Message}");
            }
            finally
            {
                Logger.WriteInfo("__MACRO_NAME__ finished.");
            }
        }

        private void ProcessOrder(Guid orderId)
        {
            try
            {
                var order = ExecuteApi("GetOrderById", () => Api.Orders.GetOrderById(orderId));
                if (order == null)
                {
                    Logger.WriteError($"Order not found. NumOrderId lookup unavailable for {orderId}.");
                    return;
                }

                // TODO: idempotency check before any mutation - see macro_conventions.md
                // rule 6 and 01_ShopifyPaymentMethodMapping.cs's
                // EnsureProcessedIdentifierExists for the reference pattern.

                // TODO: actual macro logic here. Log order.NumOrderId in every line,
                // never orderId (macro_conventions.md rule 3).
            }
            catch (Exception ex)
            {
                Logger.WriteError($"Error processing order: {ex.Message}");
            }
        }

__RATE_LIMIT_HELPERS__
    }
}
'''

# Scheduled shape mirrors scheduled_macro.md's own example: no OrderIds, scalar
# config params only, elapsed-time + processed-count in the final log line. Each
# param gets an XML <param> doc comment (see 03_PickListMonitoring.cs) - that's
# what Linnworks' macro settings UI shows as the field label/description, so an
# undocumented parameter is a real gap for whoever configures the macro, not a
# style nit.
_SCHEDULED_TEMPLATE = '''\
using System;
using System.Collections.Generic;
using System.Net;
using System.Threading;
using LinnworksMacroHelpers;

namespace __MACRO_NAME__
{
    public class __MACRO_NAME__ : LinnworksMacroBase
    {
        private const int PageSize = 200;

        /// <summary>
        /// Scheduled entry point.
        /// </summary>
__CONFIG_PARAMS_DOC__
        public void Execute(__CONFIG_PARAMS__)
        {
            var startedUtc = DateTime.UtcNow;
            var processed = 0;

            try
            {
                Logger.WriteInfo("__MACRO_NAME__ started.");

                // TODO: load this macro's working set, paged (PageNumber/EntriesPerPage,
                // looping until a short page signals the end) - never fetch "all X" in
                // one unbounded call (macro_conventions.md rule 7). See
                // 02_ContainerEtaFolderSync.cs / 03_PickListMonitoring.cs for real
                // paging, and macro_conventions.md rule 5 for choosing a server-side
                // filter/endpoint before writing this loop.

                // TODO: for each record -
                //   - idempotency check before any mutation (macro_conventions.md rule 6)
                //   - actual macro logic, every Api.* call routed through ExecuteApi
                //   - log a human-readable id (e.g. order.NumOrderId), never a raw Guid
                //   - processed++;
            }
            catch (Exception ex)
            {
                Logger.WriteError($"__MACRO_NAME__ failed: {ex}");
            }
            finally
            {
                var elapsed = DateTime.UtcNow - startedUtc;
                Logger.WriteInfo($"__MACRO_NAME__ finished in {elapsed.TotalSeconds:N1}s. Processed: {processed}.");
            }
        }

__RATE_LIMIT_HELPERS__
    }
}
'''


_PARAM_LIST_SEP = "|"
_PARAM_NAME_DESC_SEP = ":"


def _parse_config_params(config_params: str):
    """Parse "name:description|name:description" into [(name, description), ...].
    Returns a string error message instead of a list if the input is malformed -
    callers must check `isinstance(result, str)` before using it as a list."""
    entries = []
    for raw in config_params.split(_PARAM_LIST_SEP):
        raw = raw.strip()
        if not raw:
            continue
        if _PARAM_NAME_DESC_SEP not in raw:
            return (
                f'"{raw}" in config_params is missing a description. config_params must be '
                f'"name:description" pairs separated by "|", e.g. '
                f'"locationName:Name of the stock location to scan|maxOrders:Maximum number of '
                f'orders to process this run". Every Execute parameter needs a human-readable '
                f"description, because Linnworks' macro settings UI shows it to whoever configures "
                f'the macro (see how 03_PickListMonitoring.cs documents its Execute parameters with '
                f"XML <param> comments) - a bare parameter name by itself isn't enough."
            )
        name, description = raw.split(_PARAM_NAME_DESC_SEP, 1)
        name, description = name.strip(), description.strip()
        if not _MACRO_NAME_RE.match(name):
            return f'"{name}" in config_params is not a valid C# parameter name.'
        if not description:
            return f'"{name}" in config_params has an empty description - every parameter needs one (see above).'
        entries.append((name, description))
    return entries


@mcp.tool()
def scaffold_macro(macro_name: str, trigger: str, config_params: str = "") -> str:
    """Generate a starting skeleton for a new macro that already has the mandatory
    structure from get_macro_conventions() filled in, instead of leaving the caller
    to reproduce it from prose each time: start/end logging (rule 2), top-level
    try/catch/finally (rule 1), per-order error isolation for Rule macros, the full
    rate-limit-safe ExecuteApi/PaceApiCall wrapper (rule 4), and an XML <param> doc
    comment for every Execute parameter (rule 8) - each parameter is always a plain
    `string` (Linnworks' macro settings UI only edits text fields; parse/validate
    inside Execute if you need a number/Guid/bool). The business logic is left as
    TODO comments pointing at the relevant convention/golden-example - this removes
    the boilerplate a macro is required to have, it does not write the macro's
    actual purpose for you.

    macro_name: PascalCase identifier used as both the namespace and class name
    (e.g. "OrderSyncMacro"). Real approved macros each use their own distinct name
    (see golden_examples/ - "Shopify_PaymentMethod_Mapping_MacroGraphQL",
    "ContainerEtaFolderSync") - there is no fixed platform-wide macro class name to
    match, so name this for what the macro actually does, don't default to a
    placeholder like "LinnworksMacro".

    trigger: "rule" or "scheduled" - decides the Execute signature. A macro is one
    or the other, never both (macro_conventions.md rule 1.1 - a real submitted
    macro got this wrong with two Execute overloads). If genuinely unclear which
    one a requirement calls for, read rule_macro.md/scheduled_macro.md and decide
    based on the actual trigger semantics described, or ask - don't guess and don't
    hedge by writing both into one macro.

    config_params: "name:description" pairs separated by "|", one per configurable
    value the macro needs - e.g. "locationName:Name of the stock location to
    scan|maxOrders:Maximum number of orders to process this run". Never combine
    several values into one JSON- or CSV-blob parameter for the caller to parse -
    Linnworks' macro settings UI edits one text field per Execute parameter, so a
    blob parameter isn't user-editable there and defeats the point (rule 8). For a
    rule macro these are appended after the mandatory `Guid[] OrderIds` (mirrors
    01_ShopifyPaymentMethodMapping.cs's real `Execute(Guid[] OrderIds, string
    Source, ...)` shape) and may be left blank if the macro needs no extra config.
    For a scheduled macro, at least one is required - a scheduled macro has no
    OrderIds and needs some way to know its working set (leaving this blank
    generates one placeholder `someParam` with a TODO description, but that's a
    prompt to go back and name/describe the real parameter, not a valid final state).

    This is a starting point, not a finished macro - run check_against_standards
    and check_macro_compiles on the result after filling in the TODOs, same as any
    other macro."""
    if not _MACRO_NAME_RE.match(macro_name):
        return (
            f'"{macro_name}" is not a valid C# identifier - macro_name must start with '
            f"a letter or underscore and contain only letters/digits/underscores "
            f'(e.g. "OrderSyncMacro"), since it is used as both the namespace and class name.'
        )

    trigger_normalized = trigger.strip().lower()
    if trigger_normalized not in ("rule", "scheduled"):
        return f'trigger must be "rule" or "scheduled", got "{trigger}".'

    extra_params = _parse_config_params(config_params)
    if isinstance(extra_params, str):
        return extra_params

    if trigger_normalized == "rule":
        params_doc = ['/// <param name="OrderIds">Order IDs matched by the Rules Engine condition that triggered this macro.</param>']
        params_decl = ["Guid[] OrderIds"]
        for name, description in extra_params:
            params_doc.append(f'/// <param name="{name}">{description}</param>')
            params_decl.append(f'string {name} = ""')
        template = (
            _RULE_TEMPLATE.replace("__PARAMS_DOC__", "\n".join(f"        {d}" for d in params_doc))
            .replace("__PARAMS_DECL__", ", ".join(params_decl))
        )
    else:
        if not extra_params:
            extra_params = [("someParam", "TODO: describe what this parameter controls and how someone configuring the macro should set it.")]
        params_doc = [f'/// <param name="{name}">{description}</param>' for name, description in extra_params]
        params_decl = [f'string {name} = ""' for name, _ in extra_params]
        template = (
            _SCHEDULED_TEMPLATE.replace("__CONFIG_PARAMS_DOC__", "\n".join(f"        {d}" for d in params_doc))
            .replace("__CONFIG_PARAMS__", ", ".join(params_decl))
        )

    code = (
        template.replace("__RATE_LIMIT_HELPERS__", _RATE_LIMIT_HELPERS)
        .replace("__MACRO_NAME__", macro_name)
    )
    return code


# Rules below are only the ones from references/standards/conventions.md that are
# mechanically checkable with a regex over a code snippet - it is NOT a C# compiler
# and cannot see across files (e.g. it can't verify a Models/ file's filename matches
# its class name). Findings are advisory: read them, don't treat a clean report as
# proof the code is correct.
_VALUE_TYPES = ("Guid", "Int32", "Int64", "Boolean", "DateTime", "Double")
_NULLABLE_REF_TYPE_RE = re.compile(
    r"\b(String|List<[^>]*>|Dictionary<[^>]*>|IEnumerable<[^>]*>)\?"
)
_ENUM_DECL_RE = re.compile(r"public\s+enum\s+\w+")
_STRING_ENUM_CONVERTER_RE = re.compile(r"\[JsonConverter\(typeof\(StringEnumConverter\)\)\]")
_INTERFACE_DECL_RE = re.compile(r"public\s+interface\s+(\w+)")
_CONSOLE_LOG_RE = re.compile(r"\b(Console\.WriteLine|Debug\.WriteLine|Trace\.WriteLine)\s*\(")
_EMPTY_CATCH_RE = re.compile(r"catch\s*\([^)]*\)\s*\{\s*\}")
_ASYNC_RE = re.compile(r"\basync\s+(Task|void)\b")
# macro_conventions.md section 0.1 - Guid.Empty is a real location's ID, not a
# wildcard for "unfiltered". `?? Guid.Empty` is the exact shape of the confirmed
# bug in 03_PickListMonitoring.cs (92% of open orders silently invisible).
_GUID_EMPTY_DEFAULT_RE = re.compile(r"\?\?\s*Guid\.Empty\b")
_EXECUTE_SIGNATURE_RE = re.compile(r"public\s+void\s+Execute\s*\(([^)]*)\)", re.DOTALL)
_PARAM_DECL_RE = re.compile(r"(?:^|,)\s*[\w<>\[\],\s]+?\s(\w+)\s*(?:=|$)")
_PARAM_DOC_RE = re.compile(r'<param\s+name="(\w+)"')
# heuristic for macro_conventions.md rule 8 - a single Execute string parameter
# fed into a JSON/CSV parser is exactly the "one blob parameter" shape rule 8
# forbids (Linnworks' macro settings UI edits one text field per parameter, so a
# blob isn't user-editable there).
_BLOB_PARSE_RE = re.compile(r"\b(JsonConvert\.DeserializeObject|JsonFormatter\.ConvertFromJson)\s*[<(]")

# rule 10 - every Api.* call must be wrapped in ExecuteApi(...). Requires a word
# boundary before "Api." so it doesn't false-positive on an unrelated identifier
# ending in "...Api" (e.g. "someGraphqlApi.Foo()" has no \w/non-\w transition
# right before "Api.", so \b correctly doesn't match there).
_API_CALL_RE = re.compile(r"\bApi\.\w+\.\w+\s*\(")

# rule 11 - runtime-budget red flags
_INT_MAXVALUE_RE = re.compile(r"\bint\.MaxValue\b")
_THREAD_SLEEP_MS_RE = re.compile(r"Thread\.Sleep\s*\(\s*(\d+)\s*\)")
_THREAD_SLEEP_SEC_RE = re.compile(r"Thread\.Sleep\s*\(\s*TimeSpan\.FromSeconds\s*\(\s*(\d+)\s*\)\s*\)")
_SLEEP_MS_THRESHOLD = 10_000   # 10s - well above rule 4's ~550ms pacing spacing
_SLEEP_SEC_THRESHOLD = 10
_CAP_DECL_RE = re.compile(r"\b(Max\w*(?:PerRun|Orders|Records|Batch)\w*)\b\s*=")

# rule 12 - destructive operations should have a visible ownership/idempotency
# guard somewhere in the file. File-level, not per-call - "nearby in the same
# method" isn't reliably detectable with regex, so this is a coarser signal:
# does the file contain *any* destructive call and *no* marker-looking identifier
# at all. Advisory only, per the rule's own text.
_DESTRUCTIVE_CALL_RE = re.compile(r"\bApi\.\w+\.(Delete\w*|Cancel\w*|Unassign\w*|Void\w*|Discard\w*)\s*\(")
_IDEMPOTENCY_MARKER_RE = re.compile(r"\b(Marker|Processed|AlreadyHandled|Idempotenc\w*)\b", re.IGNORECASE)


def _lines_with(pattern: re.Pattern, text: str):
    return [(i, line) for i, line in enumerate(text.splitlines(), start=1) if pattern.search(line)]


# Structural checks (rule 10) need to count parens/statement boundaries without
# being confused by braces/parens that only exist inside a string or comment -
# e.g. $"GetOpenOrders(page={currentPage})" contains a literal ( and { that isn't
# real code structure. Masking replaces string/comment spans with same-length
# spaces so positions/line numbers into the original `code` stay valid.
_STRING_OR_COMMENT_RE = re.compile(
    r'@"(?:[^"]|"")*"' + r'|"(?:\\.|[^"\\])*"' + r"|'(?:\\.|[^'\\])'" + r"|//[^\n]*" + r"|/\*.*?\*/",
    re.DOTALL,
)


def _mask_strings_and_comments(text: str) -> str:
    return _STRING_OR_COMMENT_RE.sub(lambda m: " " * len(m.group(0)), text)


@mcp.tool()
def check_against_standards(code: str) -> str:
    """Lint a C# code snippet against the mechanically-checkable rules in
    references/standards/conventions.md and macro_conventions.md: nullable
    reference types (invalid in this project's C# 7.3 target), enums missing
    StringEnumConverter, interfaces not prefixed "I", logging calls inside
    SDK-layer code, empty/swallowing catch blocks, async usage (the SDK is
    synchronous throughout), `?? Guid.Empty` used as a location/vendor/category
    default (macro_conventions.md section 0.1 - a confirmed real bug shape),
    Execute parameters with no XML <param> doc comment, and a JSON/CSV blob
    standing in for several Execute parameters (macro_conventions.md rule 8). This
    is a regex linter, not a compiler - it can miss things and can false-positive.
    Read get_standards()/get_macro_conventions() for the full rules; this only
    covers the subset that's checkable without full-file/cross-file context."""
    findings = []

    for lineno, line in _lines_with(_NULLABLE_REF_TYPE_RE, code):
        findings.append(
            f"line {lineno}: nullable reference type (\"{line.strip()}\") - invalid in "
            f"C# 7.3/netstandard2.0 (this project's target). Reference types are already "
            f"nullable; drop the '?'. Value types ({', '.join(_VALUE_TYPES)}) are fine with '?'."
        )

    for lineno, line in _lines_with(_ENUM_DECL_RE, code):
        # look at the line immediately above for the converter attribute
        all_lines = code.splitlines()
        prev = all_lines[lineno - 2] if lineno >= 2 else ""
        if not _STRING_ENUM_CONVERTER_RE.search(prev):
            findings.append(
                f"line {lineno}: enum missing [JsonConverter(typeof(StringEnumConverter))] "
                f"- Linnworks enums serialize as strings, not integers; see LocalityType.cs / StateType.cs."
            )

    for lineno, line in _lines_with(_INTERFACE_DECL_RE, code):
        m = _INTERFACE_DECL_RE.search(line)
        if m and not m.group(1).startswith("I"):
            findings.append(f'line {lineno}: interface "{m.group(1)}" should be prefixed "I" (e.g. IOrdersController).')

    for lineno, line in _lines_with(_CONSOLE_LOG_RE, code):
        findings.append(
            f"line {lineno}: direct logging call in SDK-layer code (\"{line.strip()}\") - "
            f"LinnworksAPI/ doesn't log on its own; route through LinnworksMacroHelpers' "
            f"LoggerProxy/ILogger instead if this is macro code, or remove if this is SDK code."
        )

    for lineno, line in _lines_with(_EMPTY_CATCH_RE, code):
        findings.append(f"line {lineno}: empty catch block swallows the exception - catch explicitly and log, don't discard silently.")

    for lineno, line in _lines_with(_ASYNC_RE, code):
        findings.append(
            f"line {lineno}: async/await (\"{line.strip()}\") - the SDK is synchronous throughout; "
            f"introducing async here is inconsistent unless it's a deliberate, whole-SDK decision."
        )

    for lineno, line in _lines_with(_GUID_EMPTY_DEFAULT_RE, code):
        findings.append(
            f'line {lineno}: "{line.strip()}" - Guid.Empty is a real entity\'s ID (a location, vendor, '
            f'category, etc - whichever one your account has named "Default"), not a wildcard for '
            f'"unfiltered"/"all". Confirmed live (macro_conventions.md section 0.1): this exact pattern '
            f"in a real macro made 92% of the account's open orders invisible. If \"no filter\" is the "
            f"actual intent, resolve every real value (e.g. Inventory.GetStockLocations()) and "
            f"loop/branch over them explicitly instead of relying on an empty/default Guid."
        )

    execute_match = _EXECUTE_SIGNATURE_RE.search(code)
    if execute_match:
        param_names = _PARAM_DECL_RE.findall(execute_match.group(1))
        documented = set(_PARAM_DOC_RE.findall(code))
        undocumented = [p for p in param_names if p not in documented]
        if undocumented:
            findings.append(
                f"Execute parameter(s) {', '.join(undocumented)} have no XML <param name=\"...\"> doc "
                f"comment above Execute - Linnworks' macro settings UI shows that text to whoever "
                f"configures the macro (see 03_PickListMonitoring.cs), so an undocumented parameter is a "
                f"real usability gap (macro_conventions.md rule 8), not just a missing comment. Use "
                f"scaffold_macro's config_params (\"name:description\" pairs) to generate these correctly."
            )
        if _BLOB_PARSE_RE.search(code):
            findings.append(
                "Execute's body deserializes something with JsonConvert.DeserializeObject / "
                "JsonFormatter.ConvertFromJson - if that's parsing an Execute parameter rather than an "
                "external API/webhook response, that parameter is a JSON blob standing in for several "
                "config values. Linnworks' macro settings UI edits one text field per Execute parameter, "
                "so a blob isn't user-editable there - use one scalar, documented parameter per value "
                "instead (macro_conventions.md rule 8)."
            )

    # rule 10 - every Api.* call must go through a rate-limit wrapper. Real macros
    # name this wrapper differently (ExecuteApi, ApiCall, ...) and sometimes wrap
    # indirectly (a lambda passed to a batching helper that calls the real wrapper
    # internally, e.g. 02_ContainerEtaFolderSync.cs's ExecuteInBatches) - so this
    # can't check for one hardcoded name. Instead: is the Api.* call nested inside
    # *any* still-open call - i.e. is there an unmatched "(" before it that hasn't
    # been closed yet. Braces don't affect this: a block-bodied lambda argument
    # ("batch => { ... }") is still inside its enclosing call's parens the whole
    # time, so only "(" / ")" are tracked, not "{" / "}". A bare call (paren depth
    # 0 at the call site) has no wrapper by definition, whatever it's named.
    _masked = _mask_strings_and_comments(code)
    _paren_depth_at = [0] * (len(_masked) + 1)
    _depth = 0
    for _i, _ch in enumerate(_masked):
        if _ch == "(":
            _depth += 1
        elif _ch == ")":
            _depth -= 1
        _paren_depth_at[_i + 1] = _depth

    for match in _API_CALL_RE.finditer(_masked):
        if _paren_depth_at[match.start()] <= 0:
            lineno = code.count("\n", 0, match.start()) + 1
            call_line = code.splitlines()[lineno - 1].strip()
            findings.append(
                f'line {lineno}: "{call_line}" - a bare Api.* call, not nested inside any wrapping '
                f"call. Rule 4/10: every Api.* call must go through a rate-limit-safe wrapper (proactive "
                f"pacing + HTTP 429 backoff) - directly, or indirectly via a batching helper that calls "
                f"one internally (see get_macro_conventions rule 4)."
            )

    # rule 11 - runtime-budget red flags
    for lineno, line in _lines_with(_INT_MAXVALUE_RE, code):
        findings.append(
            f'line {lineno}: "{line.strip()}" - int.MaxValue in what looks like a fetch/page-size '
            f"argument requests \"no limit\", which will eventually exceed the ~5-minute budget against "
            f"a growing data set regardless of per-call speed. Page it instead (rule 7)."
        )
    for lineno, line in _lines_with(_THREAD_SLEEP_MS_RE, code):
        m = _THREAD_SLEEP_MS_RE.search(line)
        if m:
            ms = int(m.group(1))
            if ms >= _SLEEP_MS_THRESHOLD:
                findings.append(
                    f'line {lineno}: "{line.strip()}" - a literal {ms}ms (~{ms / 1000:.0f}s) sleep. Repeated '
                    f"across a batch this adds up fast against the ~5-minute budget (rule 11) - if a "
                    f"deliberate pause is really needed, make it small enough that the worst case still fits."
                )
    for lineno, line in _lines_with(_THREAD_SLEEP_SEC_RE, code):
        m = _THREAD_SLEEP_SEC_RE.search(line)
        if m:
            sec = int(m.group(1))
            if sec >= _SLEEP_SEC_THRESHOLD:
                findings.append(
                    f'line {lineno}: "{line.strip()}" - a literal {sec}s sleep. Repeated across a batch this '
                    f"adds up fast against the ~5-minute budget (rule 11) - if a deliberate pause is really "
                    f"needed, make it small enough that the worst case still fits."
                )
    for cap_name in sorted(set(_CAP_DECL_RE.findall(_masked))):
        if len(re.findall(rf"\b{re.escape(cap_name)}\b", _masked)) <= 1:
            findings.append(
                f'"{cap_name}" looks like a run-size cap that\'s declared but never referenced again - '
                f'a declared limit only does something if a loop actually checks it (e.g. "if (processed '
                f'>= {cap_name}) break;"). macro_conventions.md rule 11.'
            )

    # rule 12 - destructive operations should have a visible ownership/idempotency
    # guard somewhere in the file. File-level heuristic, advisory only - see the
    # rule's own text for why this can't be more precise than that.
    destructive_calls = sorted(set(m.group(0).rstrip(" \t(") + "(...)" for m in _DESTRUCTIVE_CALL_RE.finditer(code)))
    if destructive_calls and not _IDEMPOTENCY_MARKER_RE.search(code):
        findings.append(
            f"Destructive call(s) found ({', '.join(destructive_calls)}) but nothing in this file looks "
            f"like an idempotency/ownership marker check (no identifier containing Marker/Processed/"
            f"AlreadyHandled/Idempotency). This is a coarse, file-wide heuristic (rule 12) - it can miss a "
            f"guard written differently, or flag one enforced by the caller instead. Worth a second look, "
            f"not necessarily wrong."
        )

    if not findings:
        return "No mechanically-checkable violations found. This does not mean the code is correct - see get_standards() for rules this linter can't check (file/class naming match, LinnObject inheritance, etc)."

    return "\n".join(findings)


@mcp.tool()
def check_macro_compiles(code: str) -> str:
    """Actually compile a macro (a real `dotnet build`) against the real LinnworksAPI
    and LinnworksMacroHelpers assemblies. Catches real errors check_against_standards
    can't, since that's only a regex linter: calling a method/property that doesn't
    exist (e.g. a typo'd SDK method name), wrong argument types or counts, wrong
    namespace, missing usings.

    Compiles as net10.0/C# latest with nullable reference types enabled - the macro
    engine's own confirmed target, NOT LinnworksAPI/'s netstandard2.0/C# 7.3 (that
    constraint is SDK-library-only). Confirmed 2026-08-19 against a real account: a
    16-feature probe (records, record structs, required members, collection
    expressions, raw string literals, nullable reference types, pattern matching,
    target-typed new, null-coalescing assignment, index/range operators, using
    declarations, params collections, System.Threading.Lock, field-backed
    properties, null-conditional assignment, extension members) ran to completion -
    see references/standards/macro_conventions.md section 0 for the full results,
    including one thing NOT safe despite compiling fine locally (`file`-scoped
    types - use `internal` instead) and an unrelated open question about Rule- vs
    Scheduled-macro triggering.

    `code` must be a complete, compilable macro file - full using directives, a
    namespace, and a class deriving LinnworksMacroBase with its Execute method (see
    get_golden_example for the real shape) - not a bare snippet. Slower than
    check_against_standards (invokes the real compiler, a few seconds per call) - run
    this once a macro looks structurally right and passes check_against_standards, not
    on every draft. A clean result means the code builds and (for the 16 features
    above) matches what Linnworks' real macro engine accepts - it does not mean the
    code is logically correct or follows get_macro_conventions(), and it doesn't
    extend to language features outside that confirmed set.

    Requires the .NET SDK on this machine (the same one LinnworksAPI/ builds with);
    reports plainly if it's missing rather than failing silently."""
    if shutil.which("dotnet") is None:
        return "dotnet SDK not found on PATH - install it (https://dotnet.microsoft.com/download) to use this tool."

    with _compile_lock:
        COMPILE_CHECK_DIR.mkdir(parents=True, exist_ok=True)
        COMPILE_CHECK_SRC.write_text(code, encoding="utf-8")
        try:
            result = subprocess.run(
                ["dotnet", "build", str(COMPILE_CHECK_PROJ), "--nologo", "-v", "quiet"],
                capture_output=True,
                text=True,
                timeout=120,
                cwd=str(COMPILE_CHECK_DIR),
            )
        except subprocess.TimeoutExpired:
            return "dotnet build timed out after 120s."

    if result.returncode == 0:
        return (
            "Compiles clean against LinnworksAPI + LinnworksMacroHelpers (net10.0, C# "
            "latest, nullable enabled - the macro engine's confirmed target as of "
            "2026-08-19, see macro_conventions.md section 0). This confirms the code "
            "builds - it doesn't confirm it's logically correct, follows "
            "get_macro_conventions(), or that it uses only language features within "
            "the confirmed set (avoid `file`-scoped types specifically - see this "
            "tool's own docstring)."
        )

    output = result.stdout + result.stderr
    # dotnet repeats every error line in its trailing "Build FAILED" summary -
    # dedupe while preserving first-seen order.
    matches = list(dict.fromkeys(_COMPILE_ERROR_RE.findall(output)))
    if not matches:
        return "Build failed but no parseable compiler errors were found - raw output:\n" + output[-4000:]

    lines = [f"Macro.cs({ln},{col}): {code_} - {msg}" for ln, col, code_, msg in matches]
    return f"{len(lines)} compile error(s):\n" + "\n".join(lines)



# ---------------------------------------------------------------------------
# Knowledge layer — concepts, workflows, find_relevant_operations,
# verify_api_usage
# ---------------------------------------------------------------------------

# Directory constants
CONCEPTS_DIR = MACRO_DIR / "concepts"
WORKFLOWS_DIR = MACRO_DIR / "workflows"
LLMS_TXT_FILE = PLATFORM_ROOT / "vendor" / "llms.txt"

# ---------------------------------------------------------------------------
# Synonym expansion
# Bidirectional: any member of a group expands to all other members.
# ---------------------------------------------------------------------------
_GOAL_SYNONYMS: dict[str, list[str]] = {
    "modify": ["update", "change", "edit", "set"],
    "stock": ["inventory", "stock item", "stockitem"],
    "property": ["extended property", "extendedproperty", "metadata"],
    "shipping": ["postal service", "postalservice", "shipping service"],
    "folder": ["order folder"],
    "sku": ["item number", "itemnumber", "channel sku", "channelsku"],
}

# Pre-build: token → set of all synonymous tokens (including itself)
_SYNONYM_EXPANSION: dict[str, set[str]] = {}
for _can, _vars in _GOAL_SYNONYMS.items():
    _group = {_can} | set(_vars)
    for _t in _group:
        for _tok in re.findall(r"[a-z0-9]+", _t.lower()):
            _SYNONYM_EXPANSION.setdefault(_tok, set()).update(
                tok for phrase in _group for tok in re.findall(r"[a-z0-9]+", phrase.lower())
            )

# ---------------------------------------------------------------------------
# YAML frontmatter parser (PyYAML optional — falls back to empty dict)
# ---------------------------------------------------------------------------
try:
    import yaml as _yaml
    _HAS_YAML = True
except ImportError:  # pragma: no cover
    _HAS_YAML = False

_FM_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)


def _parse_frontmatter(text: str) -> tuple[dict, str]:
    """Return (metadata_dict, body_without_frontmatter)."""
    m = _FM_RE.match(text)
    if not m:
        return {}, text
    body = text[m.end():]
    if _HAS_YAML:
        try:
            meta = _yaml.safe_load(m.group(1)) or {}
        except Exception:
            meta = {}
    else:
        meta = {}
    return meta, body


# ---------------------------------------------------------------------------
# Section / operation / gotcha extraction helpers
# ---------------------------------------------------------------------------
_OP_LINE_RE = re.compile(r"^\s*-\s+`(\w+)\.(\w+)`\s+[—–\-]+\s+(.+)$", re.MULTILINE)
_GOTCHA_BLOCK_RE = re.compile(
    r"^###\s+(.+?)\n(.*?)(?=^###\s+|\Z)", re.MULTILINE | re.DOTALL
)
_SOURCE_INLINE_RE = re.compile(
    r"\*\*Source:\*\*\s+`([\w_]+)`\s+[—–\-]+\s+`(.+?)`"
)


def _get_section(body: str, heading: str) -> str:
    """Extract the body of a ## Heading section (stops at next ## or end-of-string)."""
    m = re.search(
        r"^##\s+" + re.escape(heading) + r"\s*\n(.*?)(?=^## |\Z)",
        body,
        re.MULTILINE | re.DOTALL,
    )
    return m.group(1) if m else ""


def _extract_operations(section_text: str) -> list[dict]:
    ops = []
    for m in _OP_LINE_RE.finditer(section_text):
        ops.append(
            {"controller": m.group(1), "method": m.group(2), "reason": m.group(3).strip()}
        )
    return ops


def _extract_gotchas(body: str) -> list[dict]:
    section = _get_section(body, "Gotchas")
    if not section:
        return []
    gotchas: list[dict] = []
    for m in _GOTCHA_BLOCK_RE.finditer(section):
        title = m.group(1).strip()
        block = m.group(2).strip()
        src_m = _SOURCE_INLINE_RE.search(block)
        clean = _SOURCE_INLINE_RE.sub("", block).strip()
        clean = re.sub(r"\n+", " ", clean).strip()
        text = f"{title}. {clean}" if clean else title
        g: dict = {"text": text}
        if src_m:
            g["source"] = {"type": src_m.group(1), "ref": src_m.group(2)}
        gotchas.append(g)
    return gotchas


# ---------------------------------------------------------------------------
# llms.txt search — title + one-line description matching
# ---------------------------------------------------------------------------
_LLMS_LINE_RE = re.compile(r"^\s*-\s+\[([^\]]+)\]\([^)]+\)(?::\s+(.+))?$")


def _search_llms_txt(query_words: set[str], max_hits: int = 8) -> list[str]:
    if not LLMS_TXT_FILE.exists():
        return []
    hits: list[str] = []
    try:
        for line in LLMS_TXT_FILE.read_text(encoding="utf-8", errors="replace").splitlines():
            m = _LLMS_LINE_RE.match(line)
            if not m:
                continue
            title = (m.group(1) or "").lower()
            desc = (m.group(2) or "").lower()
            doc_words = set(re.findall(r"[a-z0-9]+", f"{title} {desc}"))
            if any(qw in doc_words for qw in query_words):
                hits.append(m.group(2) or m.group(1))
                if len(hits) >= max_hits:
                    break
    except Exception:
        pass
    return hits


# ---------------------------------------------------------------------------
# Goal normalisation and weighted scoring
# ---------------------------------------------------------------------------
_STOP_WORDS = {"a", "an", "the", "and", "or", "to", "for", "in", "on", "at", "by", "from", "with", "is", "it", "of", "all", "each"}


def _normalize_and_expand(goal: str) -> tuple[list[str], set[str]]:
    """Return (original_tokens, expanded_token_set) after synonym expansion."""
    tokens = re.findall(r"[a-z0-9]+", goal.lower())
    expanded: set[str] = set(tokens)
    for tok in tokens:
        expanded.update(_SYNONYM_EXPANSION.get(tok, {tok}))
    return tokens, expanded


def _semantic_coverage(goal_tokens: list[str], text: str) -> float:
    """Calculates what fraction of meaningful goal tokens (or their synonyms) match in text."""
    meaningful = [t for t in goal_tokens if t not in _STOP_WORDS and len(t) > 1]
    if not meaningful:
        return 0.0
    doc_tokens = set(re.findall(r"[a-z0-9]+", text.lower()))
    matched = 0
    for tok in meaningful:
        synonyms = _SYNONYM_EXPANSION.get(tok, {tok}) | {tok}
        if any(s in doc_tokens or (len(s) >= 4 and any(d.startswith(s[:4]) for d in doc_tokens)) for s in synonyms):
            matched += 1
    return matched / len(meaningful)


def _word_score(query_words: set[str], text: str) -> float:
    """Fraction of query_words that appear in text (prefix-aware for words ≥4 chars)."""
    if not query_words:
        return 0.0
    doc_words = set(re.findall(r"[a-z0-9]+", text.lower()))
    hits = sum(
        1
        for qw in query_words
        if qw in doc_words or (len(qw) >= 4 and any(dw.startswith(qw[:4]) for dw in doc_words))
    )
    return hits / len(query_words)


# ---------------------------------------------------------------------------
# File iteration helpers
# ---------------------------------------------------------------------------
def _iter_concept_files() -> list[pathlib.Path]:
    CONCEPTS_DIR.mkdir(parents=True, exist_ok=True)
    return sorted(CONCEPTS_DIR.glob("*.md"))


def _iter_workflow_files() -> list[pathlib.Path]:
    WORKFLOWS_DIR.mkdir(parents=True, exist_ok=True)
    return sorted(WORKFLOWS_DIR.glob("*.md"))


def _load_doc(path: pathlib.Path) -> tuple[dict, str]:
    return _parse_frontmatter(_read(path))


# ---------------------------------------------------------------------------
# MCP tools — drill-down helpers
# ---------------------------------------------------------------------------
@mcp.tool()
def list_linnworks_concepts() -> str:
    """List available Linnworks concept docs (references/macro/concepts/).

    Each concept covers a Linnworks domain area: what it is, core identifiers,
    important model names, common operations, lifecycle, and gotchas with provenance.

    Use get_linnworks_concept to read one in full. Call find_relevant_operations
    first — this is a drill-down discovery tool, not the primary entry point."""
    files = _iter_concept_files()
    if not files:
        return "No concept docs found under references/macro/concepts/."
    lines = []
    for f in files:
        meta, body = _load_doc(f)
        slug = meta.get("slug", f.stem)
        title = meta.get("title", slug)
        purpose_section = _get_section(body, "Purpose")
        first_line = purpose_section.strip().split("\n")[0] if purpose_section else ""
        entry = f"{slug}: {title}"
        if first_line:
            entry += f" — {first_line[:100]}"
        lines.append(entry)
    return "\n".join(lines)


@mcp.tool()
def get_linnworks_concept(name: str) -> str:
    """Read one Linnworks concept doc in full by slug or title.

    Covers: what the entity is, core identifiers, important model names (not signatures —
    use get_model for full field lists), common operations (Controller.Method only — use
    get_endpoint for HTTP details), lifecycle, and gotchas with inline source provenance.

    Use list_linnworks_concepts to discover available concept slugs."""
    # Direct stem match
    f = _find_by_stem(CONCEPTS_DIR, name)
    if not f:
        # Fall back to title/slug match in frontmatter
        for fp in _iter_concept_files():
            meta, _ = _load_doc(fp)
            if (
                meta.get("slug", "").lower() == name.lower()
                or meta.get("title", "").lower() == name.lower()
            ):
                f = fp
                break
    if not f:
        available = [p.stem for p in _iter_concept_files()]
        return f'No concept named "{name}". Available: {", ".join(available)}'
    return _read(f)


@mcp.tool()
def list_linnworks_workflows() -> str:
    """List available Linnworks workflow docs (references/macro/workflows/).

    Each workflow covers a common macro task: intent, preconditions, step-by-step
    sequence, decision points, relevant operations (names only), and gotchas.

    Use get_linnworks_workflow to read one in full. Call find_relevant_operations
    first — this is a drill-down discovery tool, not the primary entry point."""
    files = _iter_workflow_files()
    if not files:
        return "No workflow docs found under references/macro/workflows/."
    lines = []
    for f in files:
        meta, _ = _load_doc(f)
        slug = meta.get("slug", f.stem)
        intent = meta.get("intent", "")
        entry = f"{slug}: {intent[:120]}" if intent else slug
        lines.append(entry)
    return "\n".join(lines)


@mcp.tool()
def get_linnworks_workflow(name: str) -> str:
    """Read one Linnworks workflow doc in full by slug.

    Covers: intent, preconditions, inputs, step-by-step sequence, decision points,
    relevant operations (Controller.Method + reason — use get_endpoint for signatures),
    gotchas with inline provenance, counter-cases, and related concepts/workflows.

    Use list_linnworks_workflows to discover available workflow slugs."""
    f = _find_by_stem(WORKFLOWS_DIR, name)
    if not f:
        for fp in _iter_workflow_files():
            meta, _ = _load_doc(fp)
            if meta.get("slug", "").lower() == name.lower():
                f = fp
                break
    if not f:
        available = [p.stem for p in _iter_workflow_files()]
        return f'No workflow named "{name}". Available: {", ".join(available)}'
    return _read(f)


# ---------------------------------------------------------------------------
# MCP tool — find_relevant_operations (primary knowledge entry point)
# ---------------------------------------------------------------------------
@mcp.tool()
def find_relevant_operations(goal: str) -> str:
    """Primary entry point for macro knowledge retrieval.

    Given a natural-language goal, returns structured JSON identifying: the
    best-matching workflow, relevant Linnworks concepts, candidate API operations
    (controller + method + reason), known gotchas with source provenance, match
    confidence evidence, and any ambiguities MA2 must resolve before generating code.

    Does NOT return method signatures or field details. Use get_endpoint and get_model
    for those. Always call this tool first for any new macro task.

    Search order (deterministic, weighted):
      1. Workflow docs — title, slug, intent
      2. Concept docs — title, slug, purpose section
      3. vendor/llms.txt — title + description matching (recall improvement)
      4. Existing API reference search (search_api)
    """
    import json

    goal_tokens, expanded = _normalize_and_expand(goal)

    # ------------------------------------------------------------------
    # 1. Score workflow docs
    # ------------------------------------------------------------------
    best_wf_slug: Optional[str] = None
    best_wf_score = 0.0
    wf_operations: list[dict] = []
    wf_gotchas: list[dict] = []
    wf_ambiguities: list[dict] = []

    for f in _iter_workflow_files():
        meta, body = _load_doc(f)
        slug = meta.get("slug", f.stem)
        title = meta.get("title", slug)
        intent = meta.get("intent", "")
        score = _semantic_coverage(goal_tokens, f"{slug} {title} {intent}")
        if score > best_wf_score:
            best_wf_score = score
            best_wf_slug = slug
            rel_ops_section = _get_section(body, "Relevant operations")
            wf_operations = _extract_operations(rel_ops_section)
            wf_gotchas = _extract_gotchas(body)
            wf_ambiguities = meta.get("ambiguities", []) or []

    # If workflow score is below confidence threshold (e.g. 0.40), treat as no workflow match
    if best_wf_score < 0.40:
        best_wf_slug = None
        best_wf_score = 0.0
        wf_operations = []
        wf_gotchas = []
        wf_ambiguities = []

    # ------------------------------------------------------------------
    # 2. Score concept docs
    # ------------------------------------------------------------------
    scored_concepts: list[tuple[float, str, list[dict], list[dict]]] = []

    for f in _iter_concept_files():
        meta, body = _load_doc(f)
        slug = meta.get("slug", f.stem)
        title = meta.get("title", slug)
        purpose = _get_section(body, "Purpose")
        common_ops_sec = _get_section(body, "Common operations")
        concept_ops = _extract_operations(common_ops_sec)
        
        slug_title_tokens = set(re.findall(r"[a-z0-9]+", f"{slug} {title}".lower()))
        has_direct_term = any(w in slug_title_tokens for w in expanded)
        
        score = _semantic_coverage(goal_tokens, f"{slug} {title} {purpose[:200]}")
        if has_direct_term:
            score += 0.35
            
        if score >= 0.30:
            scored_concepts.append((score, slug, _extract_gotchas(body), concept_ops))

    scored_concepts.sort(key=lambda x: x[0], reverse=True)
    matched_concepts: list[str] = []
    concept_gotchas: list[dict] = []
    concept_suggested_ops: list[dict] = []

    for _, c_slug, c_gotchas, c_ops in scored_concepts[:5]:
        matched_concepts.append(c_slug)
        concept_gotchas.extend(c_gotchas)
        if not best_wf_slug:
            concept_suggested_ops.extend(c_ops[:3])

    # ------------------------------------------------------------------
    # 3. Search llms.txt (terminology recall improvement)
    # ------------------------------------------------------------------
    llms_hits = _search_llms_txt(expanded)

    # ------------------------------------------------------------------
    # 4. Fall back to existing API reference search
    # ------------------------------------------------------------------
    api_operations: list[dict] = list(concept_suggested_ops)
    had_api_hits = False
    try:
        raw = reference_tools.search_api(goal, max_results=6)
        if "No matches" not in raw:
            had_api_hits = True
            # Parse Controller/Method pairs from lines like:
            # "OpenOrders (v1):12: ### POST `/api/OpenOrders/GetOpenOrders`"
            for m in re.finditer(
                r"/api/(\w+)/(\w+)", raw
            ):
                ctrl, meth = m.group(1), m.group(2)
                if not any(
                    op["controller"] == ctrl and op["method"] == meth
                    for op in wf_operations + api_operations
                ):
                    api_operations.append(
                        {"controller": ctrl, "method": meth, "reason": "Matched from API reference search"}
                    )
    except Exception:
        pass

    # ------------------------------------------------------------------
    # 5. Merge operations (workflow ops take precedence)
    # ------------------------------------------------------------------
    seen_ops: set[tuple[str, str]] = {(op["controller"], op["method"]) for op in wf_operations}
    for op in api_operations:
        key = (op["controller"], op["method"])
        if key not in seen_ops:
            wf_operations.append(op)
            seen_ops.add(key)
    all_operations = wf_operations[:8]

    # ------------------------------------------------------------------
    # 6. Merge gotchas (deduplicate by text prefix)
    # ------------------------------------------------------------------
    all_gotchas: list[dict] = list(wf_gotchas)
    seen_texts = {g["text"][:60] for g in all_gotchas}
    for g in concept_gotchas:
        if g["text"][:60] not in seen_texts:
            all_gotchas.append(g)
            seen_texts.add(g["text"][:60])

    # ------------------------------------------------------------------
    # 7. Compute match evidence
    # ------------------------------------------------------------------
    matched_content = f"{best_wf_slug or ''} {' '.join(matched_concepts)}"
    matched_terms = list(
        dict.fromkeys(  # preserve order, deduplicate
            tok for tok in goal_tokens if tok in matched_content.lower() or tok in expanded
        )
    )[:6]

    source_hits: list[str] = []
    if best_wf_score > 0:
        source_hits.append("workflow")
    if matched_concepts:
        source_hits.append("concept")
    if llms_hits:
        source_hits.append("llms")
    if had_api_hits:
        source_hits.append("api")

    # ------------------------------------------------------------------
    # 8. Build response
    # ------------------------------------------------------------------
    result = {
        "goal": goal,
        "match": {
            "workflow": best_wf_slug,
            "score": round(best_wf_score, 2),
            "matched_terms": matched_terms,
            "source_hits": source_hits,
        },
        "concepts": matched_concepts,
        "operations": all_operations,
        "gotchas": all_gotchas,
        "needs_more_information": wf_ambiguities,
    }

    return json.dumps(result, indent=2, ensure_ascii=False)


# ---------------------------------------------------------------------------
# MCP tool — verify_api_usage (pre-generation validation)
# ---------------------------------------------------------------------------
@mcp.tool()
def verify_api_usage(
    controller: str,
    method: str,
    model: Optional[str] = None,
    fields: Optional[list[str]] = None,
) -> str:
    """Pre-generation API verification. Confirms a controller/method pair exists in the
    endpoint reference; optionally verifies a model name and specific field names.

    Returns structured JSON with: valid flag, matched request/response models, HTTP method
    type, rate limit, field-level problems with available alternatives, and source provenance.

    This is a pre-generation conceptual check — it catches wrong field names and wrong
    controllers BEFORE code is written. It is distinct from check_macro_compiles, which
    runs the real dotnet compiler AFTER code is generated. Both are needed.

    controller: e.g. "OpenOrders", "Orders", "Inventory"
    method: e.g. "GetOpenOrders", "SetExtendedProperties"
    model: optional request model name to verify, e.g. "GetOpenOrdersRequest"
    fields: optional list of field names to verify against the model"""
    import json

    problems: list[dict] = []
    sources: list[dict] = []

    # ------------------------------------------------------------------
    # Locate controller endpoint reference file
    # ------------------------------------------------------------------
    ctrl_file: Optional[pathlib.Path] = None
    for version in ("v1", "v2"):
        ctrl_file = _find_by_stem(API_DIR / version, controller)
        if ctrl_file:
            sources.append(
                {"type": "public_api_spec", "ref": f"references/api/{version}/{ctrl_file.name}"}
            )
            break

    if not ctrl_file:
        return json.dumps(
            {
                "valid": False,
                "operation": {"controller": controller, "method": method},
                "problems": [
                    {
                        "field": None,
                        "problem": (
                            f'Controller "{controller}" not found in endpoint reference. '
                            "Use list_controllers to see available controllers."
                        ),
                        "available_matches": [],
                    }
                ],
                "request": None,
                "response": None,
                "metadata": {},
                "sources": [],
            },
            indent=2,
        )

    # Add SDK source if available
    sdk_ctrl = (
        PLATFORM_ROOT / "vendor" / "LinnworksNetSDK" / "Controllers" / f"{controller}.cs"
    )
    if sdk_ctrl.exists():
        sources.append(
            {"type": "sdk_source", "ref": f"vendor/LinnworksNetSDK/Controllers/{controller}.cs"}
        )

    ctrl_text = _read(ctrl_file)

    # ------------------------------------------------------------------
    # Find method in endpoint table
    # Table columns: | Method | Path | Summary | Rate limit | Request model | Response model |
    # The method name appears in the Path column as /api/Controller/MethodName
    # ------------------------------------------------------------------
    method_found = False
    http_method_type = ""
    rate_limit = ""
    request_model_name = ""
    response_model_name = ""

    for line in ctrl_text.splitlines():
        if "|" not in line:
            continue
        cells = [c.strip().strip("`") for c in line.split("|")[1:-1]]
        if len(cells) < 6:
            continue
        path = cells[1]
        summary = cells[2]
        if summary == method or path.rstrip("/").endswith(f"/{method}"):
            method_found = True
            http_method_type = cells[0]
            rate_limit = cells[3]
            request_model_name = cells[4] if cells[4] not in ("-", "") else ""
            response_model_name = cells[5] if cells[5] not in ("-", "") else ""
            break

    if not method_found:
        # Suggest similar methods from the path column
        available = re.findall(r"/api/\w+/(\w+)", ctrl_text)
        return json.dumps(
            {
                "valid": False,
                "operation": {"controller": controller, "method": method},
                "problems": [
                    {
                        "field": None,
                        "problem": f'Method "{method}" not found on {controller}.',
                        "available_matches": sorted(set(available))[:10],
                    }
                ],
                "request": None,
                "response": None,
                "metadata": {"rate_limit": ""},
                "sources": sources,
            },
            indent=2,
        )

    # ------------------------------------------------------------------
    # Optional: verify model fields
    # ------------------------------------------------------------------
    target_model = model or request_model_name
    verified_fields: list[str] = []
    field_problems: list[dict] = []

    if target_model and fields:
        # Find model section in endpoint reference
        model_m = re.search(
            r"### `?" + re.escape(target_model) + r"`?\s*\n(.*?)(?=\n### |\Z)",
            ctrl_text,
            re.DOTALL,
        )
        if not model_m:
            field_problems.append(
                {
                    "field": None,
                    "problem": f'Model "{target_model}" not found in {controller} reference.',
                    "available_matches": re.findall(r"### `(\w+)`", ctrl_text)[:10],
                }
            )
        else:
            model_text = model_m.group(1)
            known_fields = re.findall(r"^\|\s*`(\w+)`\s*\|", model_text, re.MULTILINE)
            for field in fields:
                if field in known_fields:
                    verified_fields.append(field)
                else:
                    close = [f for f in known_fields if field.lower() in f.lower() or f.lower() in field.lower()]
                    field_problems.append(
                        {
                            "field": field,
                            "problem": f'Field "{field}" not found on {target_model}.',
                            "available_matches": close or known_fields[:5],
                        }
                    )

    is_valid = method_found and not field_problems

    return json.dumps(
        {
            "valid": is_valid,
            "operation": {
                "controller": controller,
                "method": method,
                "http_method": http_method_type,
            },
            "request": {
                "model": target_model or None,
                "verified_fields": verified_fields or None,
            },
            "response": {
                "model": response_model_name or None,
            },
            "metadata": {
                "rate_limit": rate_limit,
            },
            "problems": field_problems,
            "sources": sources,
        },
        indent=2,
        ensure_ascii=False,
    )


def main():

    parser = argparse.ArgumentParser()
    add_http_args(parser, default_port=8788)
    args = parser.parse_args()

    if args.http:
        mcp.settings.host = args.host
        mcp.settings.port = args.port
        configure_transport_security(mcp, args.allowed_host)
        mcp.run(transport="streamable-http")
    else:
        mcp.run(transport="stdio")


if __name__ == "__main__":
    main()
