"""
Local MCP server exposing everything under references/ and migration/STATUS.md so
any MCP-compatible AI (Claude, Cursor, Antigravity, VS Code Copilot, etc.) can query
the Linnworks platform's knowledge base directly instead of having it pasted into a
system prompt. Read-only - this server never calls the real Linnworks API, it only
reads local markdown/docs generated by the scripts/ pipeline.

Run:
    python server.py                    # stdio transport, for Claude Desktop / Cursor / etc.

Claude Desktop config (claude_desktop_config.json):
    {
      "mcpServers": {
        "linnworks-platform": {
          "command": "python",
          "args": ["C:\\path\\to\\linnworks-platform\\mcp-server\\server.py"]
        }
      }
    }
"""

import re
import pathlib
from typing import Optional

from mcp.server.fastmcp import FastMCP

PLATFORM_ROOT = pathlib.Path(__file__).resolve().parent.parent
API_DIR = PLATFORM_ROOT / "references" / "api"
MACRO_DIR = PLATFORM_ROOT / "references" / "macro"
STANDARDS_DIR = PLATFORM_ROOT / "references" / "standards"
STATUS_FILE = PLATFORM_ROOT / "migration" / "STATUS.md"

mcp = FastMCP(
    "linnworks-platform",
    instructions=(
        "Reference layer for the Linnworks API and macro helpers. Prefer these tools "
        "over general knowledge for anything about Linnworks endpoints, models, rate "
        "limits, or macro FTP/SFTP/Email/Dropbox integration patterns - the underlying "
        "SDK (LinnworksAPI/) and this reference set are kept in sync with Linnworks' "
        "own published specs, general knowledge is not."
    ),
)


def _read(path: pathlib.Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def _find_controller_file(controller: str, version: str) -> Optional[pathlib.Path]:
    version_dir = API_DIR / version
    if not version_dir.exists():
        return None
    for f in version_dir.glob("*.md"):
        if f.stem.lower() == controller.lower():
            return f
    return None


@mcp.tool()
def list_controllers(status: Optional[str] = None) -> str:
    """List every Linnworks API controller tracked in migration/STATUS.md, with its
    API version and migration status. Optionally filter by status
    (done / generated / in-review / todo). Use this to discover what's available
    before calling get_endpoint."""
    if not STATUS_FILE.exists():
        return "migration/STATUS.md not found."
    rows = []
    for line in _read(STATUS_FILE).splitlines():
        if not line.startswith("|") or line.startswith("|---") or line.startswith("| Controller"):
            continue
        cols = [c.strip() for c in line.strip("|").split("|")]
        if len(cols) != 6:
            continue
        controller, spec_version, api_version, last_synced, row_status, notes = cols
        if status and row_status.lower() != status.lower():
            continue
        rows.append(f"{controller} ({api_version}) - {row_status}" + (f" - {notes}" if notes else ""))
    return "\n".join(rows) if rows else f"No controllers found with status={status!r}."


@mcp.tool()
def get_endpoint(controller: str, version: str = "v1") -> str:
    """Get the full endpoint reference for one controller: every HTTP method/path,
    rate limits, parameters, and referenced models. version is "v1" or "v2".
    Controller name is case-insensitive (e.g. "orders", "Orders", "ORDERS")."""
    f = _find_controller_file(controller, version)
    if not f:
        available = sorted(p.stem for p in (API_DIR / version).glob("*.md")) if (API_DIR / version).exists() else []
        return f'No {version} controller named "{controller}". Available: {", ".join(available)}'
    return _read(f)


@mcp.tool()
def search_api(query: str, version: Optional[str] = None, max_results: int = 15) -> str:
    """Full-text search across every controller's endpoint reference (both v1 and v2
    unless version is specified). Matches endpoint paths, method names, model names,
    and descriptions. Use this when you don't know which controller an endpoint lives
    in - e.g. search_api("fulfillment status") or search_api("stock take")."""
    versions = [version] if version else ["v1", "v2"]
    pattern = re.compile(re.escape(query), re.IGNORECASE)
    results = []
    for v in versions:
        vdir = API_DIR / v
        if not vdir.exists():
            continue
        for f in sorted(vdir.glob("*.md")):
            for i, line in enumerate(_read(f).splitlines(), start=1):
                if pattern.search(line):
                    results.append(f"{f.stem} ({v}):{i}: {line.strip()}")
                    if len(results) >= max_results:
                        break
            if len(results) >= max_results:
                break
        if len(results) >= max_results:
            break
    if not results:
        return f'No matches for "{query}".'
    return "\n".join(results)


@mcp.tool()
def get_model(name: str, version: Optional[str] = None) -> str:
    """Get one model/schema's field table by name (e.g. "StockLocation",
    "GetOrdersResponse"). Searches every controller's docs since a model can be
    referenced from more than one. Returns every match if the same name appears in
    multiple controllers' docs."""
    versions = [version] if version else ["v1", "v2"]
    heading_re = re.compile(r"^### `?" + re.escape(name) + r"`?\s*$")
    matches = []
    for v in versions:
        vdir = API_DIR / v
        if not vdir.exists():
            continue
        for f in sorted(vdir.glob("*.md")):
            lines = _read(f).splitlines()
            for i, line in enumerate(lines):
                if heading_re.match(line.strip()):
                    section = [line]
                    for j in range(i + 1, len(lines)):
                        if lines[j].startswith("## ") or lines[j].startswith("### "):
                            break
                        section.append(lines[j])
                    matches.append(f"--- from {f.stem} ({v}) ---\n" + "\n".join(section).strip())
    if not matches:
        return f'No model named "{name}" found.'
    return "\n\n".join(matches)


@mcp.tool()
def get_macro_calling_guide() -> str:
    """Get the calling-convention guide for reaching LinnworksAPI from a macro:
    the difference between running inside Linnworks' own macro engine
    (LinnworksMacroBase, pre-authenticated Api property) versus standalone code
    (manual AuthorizeByApplication + ApiObjectManager), session lifetime, and how
    errors surface. Read this before writing macro code that calls the SDK - it's
    thin by design and doesn't duplicate endpoint docs (use search_api/get_endpoint
    for those)."""
    f = MACRO_DIR / "linnworks-api" / "overview.md"
    if not f.exists():
        return "references/macro/linnworks-api/overview.md not found."
    return _read(f)


@mcp.tool()
def get_macro_integration(category: str) -> str:
    """Get macro integration reference for FTP/SFTP/Email/Dropbox/raw-HTTP: the
    IProxyHelper contract, request/response types, and real working call-site code
    from LinnMacroCustomer. category is one of: ftp, ftps, sftp, email, dropbox, web."""
    f = MACRO_DIR / "integrations" / f"{category.lower()}.md"
    if not f.exists():
        available = sorted(p.stem for p in (MACRO_DIR / "integrations").glob("*.md"))
        return f'No macro integration named "{category}". Available: {", ".join(available)}'
    return _read(f)


@mcp.tool()
def list_macro_patterns() -> str:
    """List hand-written macro pattern docs (references/macro/patterns/) - things a
    developer figured out that aren't derivable from code or the API spec alone
    (gotchas, non-obvious sequencing, workarounds). Call get_macro_pattern to read one."""
    patterns_dir = MACRO_DIR / "patterns"
    names = sorted(p.stem for p in patterns_dir.glob("*.md") if p.stem != "_template")
    if not names:
        return "No macro patterns written yet."
    return "\n".join(names)


@mcp.tool()
def get_macro_pattern(name: str) -> str:
    """Read one hand-written macro pattern doc by name (see list_macro_patterns)."""
    f = MACRO_DIR / "patterns" / f"{name}.md"
    if not f.exists():
        return f'No macro pattern named "{name}". Call list_macro_patterns for available names.'
    return _read(f)


@mcp.tool()
def get_standards() -> str:
    """Get the coding conventions macros/plugins generated against this platform
    should follow (naming, error handling, logging)."""
    f = STANDARDS_DIR / "conventions.md"
    if not f.exists():
        return "references/standards/conventions.md not found."
    return _read(f)


@mcp.tool()
def get_macro_conventions() -> str:
    """Get macro-authoring conventions derived from real approved macros: mandatory
    structure, start/end logging, human-readable IDs only in logs (never raw GUIDs),
    the required rate-limit-safe API-calling pattern (proactive pacing + exponential
    backoff on HTTP 429 - with a ready-to-use code template), server-side filter/
    endpoint selection guidance, and idempotency requirements for mutating macros.
    Read this before writing or reviewing any macro. See also list_golden_examples/
    get_golden_example for the real macros these rules were derived from."""
    f = STANDARDS_DIR / "macro_conventions.md"
    if not f.exists():
        return "references/standards/macro_conventions.md not found."
    return _read(f)


@mcp.tool()
def list_golden_examples() -> str:
    """List real, approved macros kept as reference examples, with a one-line
    summary of what each demonstrates. Call get_golden_example to read one, or read
    references/standards/golden_examples/README.md (via get_golden_example_notes)
    for the full annotated breakdown of what to copy and what to fix in each."""
    examples_dir = STANDARDS_DIR / "golden_examples"
    files = sorted(examples_dir.glob("*.cs"))
    if not files:
        return "No golden example macros yet."
    return "\n".join(f.stem for f in files)


@mcp.tool()
def get_golden_example(name: str) -> str:
    """Read one golden example macro's full source by name (see list_golden_examples).
    These are real approved macros - not all of them are fully compliant with
    get_macro_conventions()'s rules; call get_golden_example_notes for what to copy
    vs fix in each before using one as a template."""
    examples_dir = STANDARDS_DIR / "golden_examples"
    matches = [f for f in examples_dir.glob("*.cs") if f.stem == name or f.stem.lower() == name.lower()]
    if not matches:
        available = sorted(f.stem for f in examples_dir.glob("*.cs"))
        return f'No golden example named "{name}". Available: {", ".join(available)}'
    return _read(matches[0])


@mcp.tool()
def get_golden_example_notes() -> str:
    """Get the annotated breakdown of every golden example macro: what each one
    demonstrates well (copy this) and where it violates get_macro_conventions()'s
    rules (fix this if reusing). Read this before using any golden example as a
    template - none of them are perfect."""
    f = STANDARDS_DIR / "golden_examples" / "README.md"
    if not f.exists():
        return "references/standards/golden_examples/README.md not found."
    return _read(f)


# Rules below are only the ones from references/standards/conventions.md that are
# mechanically checkable with a regex over a code snippet - it is NOT a C# compiler
# and cannot see across files (e.g. it can't verify a Models/ file's filename matches
# its class name). Findings are advisory: read them, don't treat a clean report as
# proof the code is correct.
_VALUE_TYPES = ("Guid", "Int32", "Int64", "Boolean", "DateTime", "Double")
_NULLABLE_REF_TYPE_RE = re.compile(
    r"\b(String|List<[^>]*>|Dictionary<[^>]*>|IEnumerable<[^>]*>)\?"
)
_ENUM_DECL_RE = re.compile(r"public\s+enum\s+\w+")
_STRING_ENUM_CONVERTER_RE = re.compile(r"\[JsonConverter\(typeof\(StringEnumConverter\)\)\]")
_INTERFACE_DECL_RE = re.compile(r"public\s+interface\s+(\w+)")
_CONSOLE_LOG_RE = re.compile(r"\b(Console\.WriteLine|Debug\.WriteLine|Trace\.WriteLine)\s*\(")
_EMPTY_CATCH_RE = re.compile(r"catch\s*\([^)]*\)\s*\{\s*\}")
_ASYNC_RE = re.compile(r"\basync\s+(Task|void)\b")


def _lines_with(pattern: re.Pattern, text: str):
    return [(i, line) for i, line in enumerate(text.splitlines(), start=1) if pattern.search(line)]


@mcp.tool()
def check_against_standards(code: str) -> str:
    """Lint a C# code snippet against the mechanically-checkable rules in
    references/standards/conventions.md: nullable reference types (invalid in this
    project's C# 7.3 target), enums missing StringEnumConverter, interfaces not
    prefixed "I", logging calls inside SDK-layer code, empty/swallowing catch
    blocks, and async usage (the SDK is synchronous throughout). This is a regex
    linter, not a compiler - it can miss things and can false-positive. Read
    get_standards() for the full rules; this only covers the subset that's
    checkable without full-file/cross-file context."""
    findings = []

    for lineno, line in _lines_with(_NULLABLE_REF_TYPE_RE, code):
        findings.append(
            f"line {lineno}: nullable reference type (\"{line.strip()}\") - invalid in "
            f"C# 7.3/netstandard2.0 (this project's target). Reference types are already "
            f"nullable; drop the '?'. Value types ({', '.join(_VALUE_TYPES)}) are fine with '?'."
        )

    for lineno, line in _lines_with(_ENUM_DECL_RE, code):
        # look at the line immediately above for the converter attribute
        all_lines = code.splitlines()
        prev = all_lines[lineno - 2] if lineno >= 2 else ""
        if not _STRING_ENUM_CONVERTER_RE.search(prev):
            findings.append(
                f"line {lineno}: enum missing [JsonConverter(typeof(StringEnumConverter))] "
                f"- Linnworks enums serialize as strings, not integers; see LocalityType.cs / StateType.cs."
            )

    for lineno, line in _lines_with(_INTERFACE_DECL_RE, code):
        m = _INTERFACE_DECL_RE.search(line)
        if m and not m.group(1).startswith("I"):
            findings.append(f'line {lineno}: interface "{m.group(1)}" should be prefixed "I" (e.g. IOrdersController).')

    for lineno, line in _lines_with(_CONSOLE_LOG_RE, code):
        findings.append(
            f"line {lineno}: direct logging call in SDK-layer code (\"{line.strip()}\") - "
            f"LinnworksAPI/ doesn't log on its own; route through LinnworksMacroHelpers' "
            f"LoggerProxy/ILogger instead if this is macro code, or remove if this is SDK code."
        )

    for lineno, line in _lines_with(_EMPTY_CATCH_RE, code):
        findings.append(f"line {lineno}: empty catch block swallows the exception - catch explicitly and log, don't discard silently.")

    for lineno, line in _lines_with(_ASYNC_RE, code):
        findings.append(
            f"line {lineno}: async/await (\"{line.strip()}\") - the SDK is synchronous throughout; "
            f"introducing async here is inconsistent unless it's a deliberate, whole-SDK decision."
        )

    if not findings:
        return "No mechanically-checkable violations found. This does not mean the code is correct - see get_standards() for rules this linter can't check (file/class naming match, LinnObject inheritance, etc)."

    return "\n".join(findings)


if __name__ == "__main__":
    mcp.run(transport="stdio")
