"""
MCP server exposing everything under references/ and migration/STATUS.md so any
MCP-compatible AI (Claude, Cursor, Antigravity, VS Code Copilot, etc.) can query
the Linnworks platform's knowledge base directly instead of having it pasted into a
system prompt. Read-only - this server never calls the real Linnworks API, it only
reads local markdown/docs generated by the scripts/ pipeline.

This is the FULL internal server - includes macro conventions, golden-example
macros, and standards linting, unlike mcp-server-api/ (the public-safe subset).
Hosting this one publicly means anyone with the URL can read your golden-example
macros and internal conventions - that's a deliberate choice, not an accident;
see README.md.

Run locally (stdio, for an IDE/AI client on this machine):
    python server.py

Run as a network service (for hosting - see README.md):
    python server.py --http --host 0.0.0.0 --port 8788

Claude Desktop config (claude_desktop_config.json), local stdio form:
    {
      "mcpServers": {
        "linnworks-platform": {
          "command": "python",
          "args": ["C:\\path\\to\\linnworks-platform\\mcp-server\\server.py"]
        }
      }
    }
"""

import argparse
import re
import pathlib
import shutil
import subprocess
import sys
import threading
from typing import Optional

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent / "mcp-shared"))
import reference_tools  # noqa: E402
from transport import add_http_args, configure_transport_security  # noqa: E402

from mcp.server.fastmcp import FastMCP

PLATFORM_ROOT = pathlib.Path(__file__).resolve().parent.parent
API_DIR = PLATFORM_ROOT / "references" / "api"
MACRO_DIR = PLATFORM_ROOT / "references" / "macro"
STANDARDS_DIR = PLATFORM_ROOT / "references" / "standards"
STATUS_FILE = PLATFORM_ROOT / "migration" / "STATUS.md"
_read = reference_tools.read_text
_find_by_stem = reference_tools.find_by_stem
COMPILE_CHECK_DIR = pathlib.Path(__file__).resolve().parent / "compile_check"
COMPILE_CHECK_PROJ = COMPILE_CHECK_DIR / "CompileCheck.csproj"
COMPILE_CHECK_SRC = COMPILE_CHECK_DIR / "Macro.cs"
_COMPILE_ERROR_RE = re.compile(r"Macro\.cs\((\d+),(\d+)\):\s+error\s+(CS\d+):\s+(.+?)\s+\[")
_compile_lock = threading.Lock()

mcp = FastMCP(
    "linnworks-platform",
    instructions=(
        "Reference layer for the Linnworks API and macro helpers. Prefer these tools "
        "over general knowledge for anything about Linnworks endpoints, models, rate "
        "limits, or macro FTP/SFTP/Email/Dropbox integration patterns - the underlying "
        "SDK (LinnworksAPI/) and this reference set are kept in sync with Linnworks' "
        "own published specs, general knowledge is not."
    ),
)


@mcp.tool()
def list_controllers(status: Optional[str] = None) -> str:
    """List every Linnworks API controller tracked in migration/STATUS.md, with its
    API version and migration status. Optionally filter by status
    (done / generated / in-review / todo). Use this to discover what's available
    before calling get_endpoint."""
    return reference_tools.list_controllers_impl(status, include_notes=True)


mcp.tool()(reference_tools.get_endpoint)
mcp.tool()(reference_tools.search_api)
mcp.tool()(reference_tools.get_model)


@mcp.tool()
def get_macro_calling_guide() -> str:
    """Get the calling-convention guide for reaching LinnworksAPI from a macro:
    the difference between running inside Linnworks' own macro engine
    (LinnworksMacroBase, pre-authenticated Api property) versus standalone code
    (manual AuthorizeByApplication + ApiObjectManager), session lifetime, and how
    errors surface. Read this before writing macro code that calls the SDK - it's
    thin by design and doesn't duplicate endpoint docs (use search_api/get_endpoint
    for those)."""
    f = MACRO_DIR / "linnworks-api" / "overview.md"
    if not f.exists():
        return "references/macro/linnworks-api/overview.md not found."
    return _read(f)


@mcp.tool()
def get_macro_integration(category: str) -> str:
    """Get macro integration reference for FTP/SFTP/Email/Dropbox/raw-HTTP: the
    IProxyHelper contract, request/response types, and real working call-site code
    from LinnMacroCustomer. category is one of: ftp, ftps, sftp, email, dropbox, web."""
    f = _find_by_stem(MACRO_DIR / "integrations", category)
    if not f:
        available = sorted(p.stem for p in (MACRO_DIR / "integrations").glob("*.md"))
        return f'No macro integration named "{category}". Available: {", ".join(available)}'
    return _read(f)


@mcp.tool()
def list_macro_patterns() -> str:
    """List hand-written macro pattern docs (references/macro/patterns/) - things a
    developer figured out that aren't derivable from code or the API spec alone
    (gotchas, non-obvious sequencing, workarounds). Call get_macro_pattern to read one."""
    patterns_dir = MACRO_DIR / "patterns"
    names = sorted(p.stem for p in patterns_dir.glob("*.md") if p.stem != "_template")
    if not names:
        return "No macro patterns written yet."
    return "\n".join(names)


@mcp.tool()
def get_macro_pattern(name: str) -> str:
    """Read one hand-written macro pattern doc by name (see list_macro_patterns)."""
    f = _find_by_stem(MACRO_DIR / "patterns", name)
    if not f:
        return f'No macro pattern named "{name}". Call list_macro_patterns for available names.'
    return _read(f)


@mcp.tool()
def get_standards() -> str:
    """Get the coding conventions macros/plugins generated against this platform
    should follow (naming, error handling, logging)."""
    f = STANDARDS_DIR / "conventions.md"
    if not f.exists():
        return "references/standards/conventions.md not found."
    return _read(f)


@mcp.tool()
def get_macro_conventions() -> str:
    """Get macro-authoring conventions derived from real approved macros: mandatory
    structure, start/end logging, human-readable IDs only in logs (never raw GUIDs),
    the required rate-limit-safe API-calling pattern (proactive pacing + exponential
    backoff on HTTP 429 - with a ready-to-use code template), server-side filter/
    endpoint selection guidance, and idempotency requirements for mutating macros.
    Read this before writing or reviewing any macro. See also list_golden_examples/
    get_golden_example for the real macros these rules were derived from."""
    f = STANDARDS_DIR / "macro_conventions.md"
    if not f.exists():
        return "references/standards/macro_conventions.md not found."
    return _read(f)


@mcp.tool()
def list_golden_examples() -> str:
    """List real, approved macros kept as reference examples, with a one-line
    summary of what each demonstrates. Call get_golden_example to read one, or read
    references/standards/golden_examples/README.md (via get_golden_example_notes)
    for the full annotated breakdown of what to copy and what to fix in each."""
    examples_dir = STANDARDS_DIR / "golden_examples"
    files = sorted(examples_dir.glob("*.cs"))
    if not files:
        return "No golden example macros yet."
    return "\n".join(f.stem for f in files)


@mcp.tool()
def get_golden_example(name: str) -> str:
    """Read one golden example macro's full source by name (see list_golden_examples).
    These are real approved macros - not all of them are fully compliant with
    get_macro_conventions()'s rules; call get_golden_example_notes for what to copy
    vs fix in each before using one as a template."""
    examples_dir = STANDARDS_DIR / "golden_examples"
    matches = [f for f in examples_dir.glob("*.cs") if f.stem == name or f.stem.lower() == name.lower()]
    if not matches:
        available = sorted(f.stem for f in examples_dir.glob("*.cs"))
        return f'No golden example named "{name}". Available: {", ".join(available)}'
    return _read(matches[0])


@mcp.tool()
def get_golden_example_notes() -> str:
    """Get the annotated breakdown of every golden example macro: what each one
    demonstrates well (copy this) and where it violates get_macro_conventions()'s
    rules (fix this if reusing). Read this before using any golden example as a
    template - none of them are perfect."""
    f = STANDARDS_DIR / "golden_examples" / "README.md"
    if not f.exists():
        return "references/standards/golden_examples/README.md not found."
    return _read(f)


_GOLDEN_EXAMPLE_SECTION_RE = re.compile(r"(?m)^## (.+\.cs)\s*$")


@mcp.tool()
def search_golden_examples(query: str, max_results: int = 5) -> str:
    """Find the closest existing golden example macro to a new requirement, without
    already knowing its filename. Searches the full annotated write-up of every
    golden example (golden_examples/README.md - what it demonstrates, what to copy,
    what to fix), not just the filename, so e.g. search_golden_examples("rate
    limit"), search_golden_examples("idempotency"), or search_golden_examples("folder
    sync") all find the relevant example even if you don't know its name. Ranked by
    match count in each example's section. Call get_golden_example(name) to read the
    full source of whichever one comes back, or get_golden_example_notes() to read
    every example's write-up at once instead of searching."""
    f = STANDARDS_DIR / "golden_examples" / "README.md"
    if not f.exists():
        return "references/standards/golden_examples/README.md not found."
    text = _read(f)
    pieces = _GOLDEN_EXAMPLE_SECTION_RE.split(text)
    # pieces[0] is the preamble before the first "## X.cs" heading; then it
    # alternates heading, body, heading, body, ...
    entries = [(pieces[i], pieces[i + 1]) for i in range(1, len(pieces) - 1, 2)]

    # Word-level, substring-within-word matching - not a literal phrase search.
    # "rate limit" needs to match text that says "rate-limit" (hyphen, not space)
    # and "folder sync" needs to match "Syncs order folders" (plural/tense
    # mismatch) - both failed under plain substring matching during testing.
    query_words = re.findall(r"[a-z0-9]+", query.lower())
    if not query_words:
        return 'Empty query - pass at least one word, e.g. search_golden_examples("rate limit").'

    def _word_matches(query_word: str, doc_word: str) -> bool:
        # Prefix relation, not "contains anywhere" - the latter false-positived on
        # short common words (e.g. "is") being trivially a substring of an unrelated
        # query word (e.g. "nonexistent" contains "is") during testing. Require
        # length >= 3 before allowing a prefix match at all, so single/double-letter
        # doc words can never drive a match.
        if query_word == doc_word:
            return True
        if len(query_word) < 3 or len(doc_word) < 3:
            return False
        return doc_word.startswith(query_word) or query_word.startswith(doc_word)

    def _word_hits(section_text: str) -> int:
        doc_words = re.findall(r"[a-z0-9]+", section_text.lower())
        return sum(1 for qw in query_words if any(_word_matches(qw, dw) for dw in doc_words))

    scored = []
    for heading, body in entries:
        heading_hits = _word_hits(heading)
        body_hits = _word_hits(body)
        score = heading_hits * 3 + body_hits
        if score > 0:
            scored.append((score, heading, body.strip()))
    if not scored:
        return (
            f'No golden example matches "{query}". Call list_golden_examples() to see '
            f"all of them, or get_golden_example_notes() to read every write-up."
        )
    scored.sort(key=lambda item: -item[0])

    results = []
    for score, heading, body in scored[:max_results]:
        snippet = body if len(body) <= 600 else body[:600].rstrip() + "..."
        results.append(f"--- {heading} (match score {score}) ---\n{snippet}")
    return "\n\n".join(results)


_MACRO_NAME_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

# Rate-limit wrapper is macro_conventions.md rule 4's exact reference pattern
# (ExecuteApi/PaceApiCall from 02_ContainerEtaFolderSync.cs) - copied verbatim, not
# reworded, so scaffold_macro's output matches what get_macro_conventions() documents
# as mandatory rather than a paraphrase that could drift from it over time.
_RATE_LIMIT_HELPERS = '''\
        private static readonly object RateLimitLock = new();
        private static DateTime _lastApiCallUtc = DateTime.MinValue;
        private const int MinimumApiSpacingMilliseconds = 550;

        private static void PaceApiCall()
        {
            lock (RateLimitLock)
            {
                var elapsed = (DateTime.UtcNow - _lastApiCallUtc).TotalMilliseconds;
                if (elapsed < MinimumApiSpacingMilliseconds)
                    Thread.Sleep(MinimumApiSpacingMilliseconds - (int)elapsed);
                _lastApiCallUtc = DateTime.UtcNow;
            }
        }

        private T ExecuteApi<T>(string operationName, Func<T> operation)
        {
            const int maxAttempts = 5;
            var retryDelaysSeconds = new[] { 5, 15, 30, 60 };
            for (var attempt = 1; attempt <= maxAttempts; attempt++)
            {
                PaceApiCall();
                try { return operation(); }
                catch (Exception ex) when (IsHttp429(ex) && attempt < maxAttempts)
                {
                    Thread.Sleep(TimeSpan.FromSeconds(retryDelaysSeconds[attempt - 1]));
                }
            }
            throw new InvalidOperationException($"{operationName} failed without returning a result.");
        }

        private static bool IsHttp429(Exception exception)
        {
            for (var current = exception; current != null; current = current.InnerException)
            {
                if (current is WebException webEx && webEx.Response is HttpWebResponse http && (int)http.StatusCode == 429)
                    return true;
                if (current.Message.Contains("error 429", StringComparison.OrdinalIgnoreCase) ||
                    current.Message.Contains("Too Many Requests", StringComparison.OrdinalIgnoreCase))
                    return true;
            }
            return false;
        }
'''

# Rule shape mirrors rule_macro.md's own example: Guid[] OrderIds first param,
# per-order try/catch delegated to a helper (one bad order can't stop the batch),
# distinct-order loop. ExecuteApi wraps the one real Api.* call already present.
_RULE_TEMPLATE = '''\
using System;
using System.Linq;
using System.Net;
using System.Threading;
using LinnworksMacroHelpers;

namespace __MACRO_NAME__
{
    public class __MACRO_NAME__ : LinnworksMacroBase
    {
        public void Execute(Guid[] OrderIds)
        {
            Logger.WriteInfo("__MACRO_NAME__ started.");

            try
            {
                if (OrderIds == null || OrderIds.Length == 0)
                {
                    Logger.WriteInfo("No OrderIds supplied. Macro exiting.");
                    return;
                }

                foreach (var orderId in OrderIds.Distinct())
                {
                    ProcessOrder(orderId);
                }
            }
            catch (Exception ex)
            {
                Logger.WriteError($"Unhandled macro error: {ex.Message}");
            }
            finally
            {
                Logger.WriteInfo("__MACRO_NAME__ finished.");
            }
        }

        private void ProcessOrder(Guid orderId)
        {
            try
            {
                var order = ExecuteApi("GetOrderById", () => Api.Orders.GetOrderById(orderId));
                if (order == null)
                {
                    Logger.WriteError($"Order not found. NumOrderId lookup unavailable for {orderId}.");
                    return;
                }

                // TODO: idempotency check before any mutation - see macro_conventions.md
                // rule 6 and 01_ShopifyPaymentMethodMapping.cs's
                // EnsureProcessedIdentifierExists for the reference pattern.

                // TODO: actual macro logic here. Log order.NumOrderId in every line,
                // never orderId (macro_conventions.md rule 3).
            }
            catch (Exception ex)
            {
                Logger.WriteError($"Error processing order: {ex.Message}");
            }
        }

__RATE_LIMIT_HELPERS__
    }
}
'''

# Scheduled shape mirrors scheduled_macro.md's own example: no OrderIds, scalar
# config params only, elapsed-time + processed-count in the final log line.
_SCHEDULED_TEMPLATE = '''\
using System;
using System.Collections.Generic;
using System.Net;
using System.Threading;
using LinnworksMacroHelpers;

namespace __MACRO_NAME__
{
    public class __MACRO_NAME__ : LinnworksMacroBase
    {
        private const int PageSize = 200;

        public void Execute(__CONFIG_PARAMS__)
        {
            var startedUtc = DateTime.UtcNow;
            var processed = 0;

            try
            {
                Logger.WriteInfo("__MACRO_NAME__ started.");

                // TODO: load this macro's working set, paged (PageNumber/EntriesPerPage,
                // looping until a short page signals the end) - never fetch "all X" in
                // one unbounded call (macro_conventions.md rule 7). See
                // 02_ContainerEtaFolderSync.cs / 03_PickListMonitoring.cs for real
                // paging, and macro_conventions.md rule 5 for choosing a server-side
                // filter/endpoint before writing this loop.

                // TODO: for each record -
                //   - idempotency check before any mutation (macro_conventions.md rule 6)
                //   - actual macro logic, every Api.* call routed through ExecuteApi
                //   - log a human-readable id (e.g. order.NumOrderId), never a raw Guid
                //   - processed++;
            }
            catch (Exception ex)
            {
                Logger.WriteError($"__MACRO_NAME__ failed: {ex}");
            }
            finally
            {
                var elapsed = DateTime.UtcNow - startedUtc;
                Logger.WriteInfo($"__MACRO_NAME__ finished in {elapsed.TotalSeconds:N1}s. Processed: {processed}.");
            }
        }

__RATE_LIMIT_HELPERS__
    }
}
'''


@mcp.tool()
def scaffold_macro(macro_name: str, trigger: str, config_params: str = "") -> str:
    """Generate a starting skeleton for a new macro that already has the mandatory
    structure from get_macro_conventions() filled in, instead of leaving the caller
    to reproduce it from prose each time: start/end logging (rule 2), top-level
    try/catch/finally (rule 1), per-order error isolation for Rule macros, and the
    full rate-limit-safe ExecuteApi/PaceApiCall wrapper (rule 4 - proactive pacing +
    HTTP 429 retry with exponential backoff, copied verbatim from
    02_ContainerEtaFolderSync.cs, the reference implementation). The business logic
    is left as TODO comments pointing at the relevant convention/golden-example -
    this removes the boilerplate a macro is required to have, it does not write the
    macro's actual purpose for you.

    macro_name: PascalCase identifier used as both the namespace and class name
    (e.g. "OrderSyncMacro"). Real approved macros each use their own distinct name
    (see golden_examples/ - "Shopify_PaymentMethod_Mapping_MacroGraphQL",
    "ContainerEtaFolderSync") - there is no fixed platform-wide macro class name to
    match, so name this for what the macro actually does, don't default to a
    placeholder like "LinnworksMacro".

    trigger: "rule" or "scheduled" - decides the Execute signature. A macro is one
    or the other, never both (macro_conventions.md rule 1.1 - a real submitted
    macro got this wrong with two Execute overloads). If genuinely unclear which
    one a requirement calls for, read rule_macro.md/scheduled_macro.md and decide
    based on the actual trigger semantics described, or ask - don't guess and don't
    hedge by writing both into one macro.

    config_params: scheduled macros only - comma-separated scalar parameter names
    (e.g. "locationName,folderPrefix"), each generated as an optional `string`
    parameter. Ignored for a rule macro, which always takes Guid[] OrderIds first.
    Leave blank for a parameterless scheduled macro (still generates one
    placeholder param, since every real scheduled golden example takes at least
    one).

    This is a starting point, not a finished macro - run check_against_standards
    and check_macro_compiles on the result after filling in the TODOs, same as any
    other macro."""
    if not _MACRO_NAME_RE.match(macro_name):
        return (
            f'"{macro_name}" is not a valid C# identifier - macro_name must start with '
            f"a letter or underscore and contain only letters/digits/underscores "
            f'(e.g. "OrderSyncMacro"), since it is used as both the namespace and class name.'
        )

    trigger_normalized = trigger.strip().lower()
    if trigger_normalized not in ("rule", "scheduled"):
        return f'trigger must be "rule" or "scheduled", got "{trigger}".'

    if trigger_normalized == "rule":
        template = _RULE_TEMPLATE
    else:
        param_names = [p.strip() for p in config_params.split(",") if p.strip()]
        if not param_names:
            param_names = ["someParam"]
        for p in param_names:
            if not _MACRO_NAME_RE.match(p):
                return f'"{p}" in config_params is not a valid C# parameter name.'
        params_declaration = ", ".join(f'string {p} = ""' for p in param_names)
        template = _SCHEDULED_TEMPLATE.replace("__CONFIG_PARAMS__", params_declaration)

    code = (
        template.replace("__RATE_LIMIT_HELPERS__", _RATE_LIMIT_HELPERS)
        .replace("__MACRO_NAME__", macro_name)
    )
    return code


# Rules below are only the ones from references/standards/conventions.md that are
# mechanically checkable with a regex over a code snippet - it is NOT a C# compiler
# and cannot see across files (e.g. it can't verify a Models/ file's filename matches
# its class name). Findings are advisory: read them, don't treat a clean report as
# proof the code is correct.
_VALUE_TYPES = ("Guid", "Int32", "Int64", "Boolean", "DateTime", "Double")
_NULLABLE_REF_TYPE_RE = re.compile(
    r"\b(String|List<[^>]*>|Dictionary<[^>]*>|IEnumerable<[^>]*>)\?"
)
_ENUM_DECL_RE = re.compile(r"public\s+enum\s+\w+")
_STRING_ENUM_CONVERTER_RE = re.compile(r"\[JsonConverter\(typeof\(StringEnumConverter\)\)\]")
_INTERFACE_DECL_RE = re.compile(r"public\s+interface\s+(\w+)")
_CONSOLE_LOG_RE = re.compile(r"\b(Console\.WriteLine|Debug\.WriteLine|Trace\.WriteLine)\s*\(")
_EMPTY_CATCH_RE = re.compile(r"catch\s*\([^)]*\)\s*\{\s*\}")
_ASYNC_RE = re.compile(r"\basync\s+(Task|void)\b")


def _lines_with(pattern: re.Pattern, text: str):
    return [(i, line) for i, line in enumerate(text.splitlines(), start=1) if pattern.search(line)]


@mcp.tool()
def check_against_standards(code: str) -> str:
    """Lint a C# code snippet against the mechanically-checkable rules in
    references/standards/conventions.md: nullable reference types (invalid in this
    project's C# 7.3 target), enums missing StringEnumConverter, interfaces not
    prefixed "I", logging calls inside SDK-layer code, empty/swallowing catch
    blocks, and async usage (the SDK is synchronous throughout). This is a regex
    linter, not a compiler - it can miss things and can false-positive. Read
    get_standards() for the full rules; this only covers the subset that's
    checkable without full-file/cross-file context."""
    findings = []

    for lineno, line in _lines_with(_NULLABLE_REF_TYPE_RE, code):
        findings.append(
            f"line {lineno}: nullable reference type (\"{line.strip()}\") - invalid in "
            f"C# 7.3/netstandard2.0 (this project's target). Reference types are already "
            f"nullable; drop the '?'. Value types ({', '.join(_VALUE_TYPES)}) are fine with '?'."
        )

    for lineno, line in _lines_with(_ENUM_DECL_RE, code):
        # look at the line immediately above for the converter attribute
        all_lines = code.splitlines()
        prev = all_lines[lineno - 2] if lineno >= 2 else ""
        if not _STRING_ENUM_CONVERTER_RE.search(prev):
            findings.append(
                f"line {lineno}: enum missing [JsonConverter(typeof(StringEnumConverter))] "
                f"- Linnworks enums serialize as strings, not integers; see LocalityType.cs / StateType.cs."
            )

    for lineno, line in _lines_with(_INTERFACE_DECL_RE, code):
        m = _INTERFACE_DECL_RE.search(line)
        if m and not m.group(1).startswith("I"):
            findings.append(f'line {lineno}: interface "{m.group(1)}" should be prefixed "I" (e.g. IOrdersController).')

    for lineno, line in _lines_with(_CONSOLE_LOG_RE, code):
        findings.append(
            f"line {lineno}: direct logging call in SDK-layer code (\"{line.strip()}\") - "
            f"LinnworksAPI/ doesn't log on its own; route through LinnworksMacroHelpers' "
            f"LoggerProxy/ILogger instead if this is macro code, or remove if this is SDK code."
        )

    for lineno, line in _lines_with(_EMPTY_CATCH_RE, code):
        findings.append(f"line {lineno}: empty catch block swallows the exception - catch explicitly and log, don't discard silently.")

    for lineno, line in _lines_with(_ASYNC_RE, code):
        findings.append(
            f"line {lineno}: async/await (\"{line.strip()}\") - the SDK is synchronous throughout; "
            f"introducing async here is inconsistent unless it's a deliberate, whole-SDK decision."
        )

    if not findings:
        return "No mechanically-checkable violations found. This does not mean the code is correct - see get_standards() for rules this linter can't check (file/class naming match, LinnObject inheritance, etc)."

    return "\n".join(findings)


@mcp.tool()
def check_macro_compiles(code: str) -> str:
    """Actually compile a macro (a real `dotnet build`) against the real LinnworksAPI
    and LinnworksMacroHelpers assemblies. Catches real errors check_against_standards
    can't, since that's only a regex linter: calling a method/property that doesn't
    exist (e.g. a typo'd SDK method name), wrong argument types or counts, wrong
    namespace, missing usings.

    Compiles as net10.0/C# latest with nullable reference types enabled - the macro
    engine's own confirmed target, NOT LinnworksAPI/'s netstandard2.0/C# 7.3 (that
    constraint is SDK-library-only). Confirmed 2026-08-19 against a real account: a
    16-feature probe (records, record structs, required members, collection
    expressions, raw string literals, nullable reference types, pattern matching,
    target-typed new, null-coalescing assignment, index/range operators, using
    declarations, params collections, System.Threading.Lock, field-backed
    properties, null-conditional assignment, extension members) ran to completion -
    see references/standards/macro_conventions.md section 0 for the full results,
    including one thing NOT safe despite compiling fine locally (`file`-scoped
    types - use `internal` instead) and an unrelated open question about Rule- vs
    Scheduled-macro triggering.

    `code` must be a complete, compilable macro file - full using directives, a
    namespace, and a class deriving LinnworksMacroBase with its Execute method (see
    get_golden_example for the real shape) - not a bare snippet. Slower than
    check_against_standards (invokes the real compiler, a few seconds per call) - run
    this once a macro looks structurally right and passes check_against_standards, not
    on every draft. A clean result means the code builds and (for the 16 features
    above) matches what Linnworks' real macro engine accepts - it does not mean the
    code is logically correct or follows get_macro_conventions(), and it doesn't
    extend to language features outside that confirmed set.

    Requires the .NET SDK on this machine (the same one LinnworksAPI/ builds with);
    reports plainly if it's missing rather than failing silently."""
    if shutil.which("dotnet") is None:
        return "dotnet SDK not found on PATH - install it (https://dotnet.microsoft.com/download) to use this tool."

    with _compile_lock:
        COMPILE_CHECK_DIR.mkdir(parents=True, exist_ok=True)
        COMPILE_CHECK_SRC.write_text(code, encoding="utf-8")
        try:
            result = subprocess.run(
                ["dotnet", "build", str(COMPILE_CHECK_PROJ), "--nologo", "-v", "quiet"],
                capture_output=True,
                text=True,
                timeout=120,
                cwd=str(COMPILE_CHECK_DIR),
            )
        except subprocess.TimeoutExpired:
            return "dotnet build timed out after 120s."

    if result.returncode == 0:
        return (
            "Compiles clean against LinnworksAPI + LinnworksMacroHelpers (net10.0, C# "
            "latest, nullable enabled - the macro engine's confirmed target as of "
            "2026-08-19, see macro_conventions.md section 0). This confirms the code "
            "builds - it doesn't confirm it's logically correct, follows "
            "get_macro_conventions(), or that it uses only language features within "
            "the confirmed set (avoid `file`-scoped types specifically - see this "
            "tool's own docstring)."
        )

    output = result.stdout + result.stderr
    # dotnet repeats every error line in its trailing "Build FAILED" summary -
    # dedupe while preserving first-seen order.
    matches = list(dict.fromkeys(_COMPILE_ERROR_RE.findall(output)))
    if not matches:
        return "Build failed but no parseable compiler errors were found - raw output:\n" + output[-4000:]

    lines = [f"Macro.cs({ln},{col}): {code_} - {msg}" for ln, col, code_, msg in matches]
    return f"{len(lines)} compile error(s):\n" + "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    add_http_args(parser, default_port=8788)
    args = parser.parse_args()

    if args.http:
        mcp.settings.host = args.host
        mcp.settings.port = args.port
        configure_transport_security(mcp, args.allowed_host)
        mcp.run(transport="streamable-http")
    else:
        mcp.run(transport="stdio")


if __name__ == "__main__":
    main()
