<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
	<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <ApplicationIcon />
    <OutputType>Exe</OutputType>
    <StartupObject />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentFTP" Version="51.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LinnworksAPI\LinnworksAPI.csproj" />
    <ProjectReference Include="..\LinnworksMacro\LinnworksMacro.csproj" />
  </ItemGroup>

</Project>
