"""
Scans the macro helper code (LinnworksMacroHelpers/Classes/*, LinnMacroCustomer/*,
both now local to this repo) and regenerates references/macro/integrations/*.md.

Never hand-edit the generated .md files - edit the source .cs class instead and
re-run this script. Extraction is regex-based (not a real C# parser), so it is
"good enough for docs", not a compiler. If a file's structure breaks the regexes,
fix the regex here rather than hand-patching the .md output.

Usage:
    python sync_macro_integrations.py
    python sync_macro_integrations.py --old-repo "C:\\path\\to\\a-different-checkout"
    python sync_macro_integrations.py --category ftp
"""

import argparse
import datetime
import pathlib
import re
import sys

PLATFORM_ROOT = pathlib.Path(__file__).resolve().parent.parent
DEFAULT_OLD_REPO = PLATFORM_ROOT
OUTPUT_DIR = PLATFORM_ROOT / "references" / "macro" / "integrations"

# One entry per generated doc. `dirs` are class/model source folders (relative to
# the old repo root) scanned for public types. `include`/`exclude` are lowercase
# substrings used to pull matching usage methods out of the proxy factory (the
# actual call-site implementation) - camelCase method names have no \b word
# boundaries between tokens (e.g. "DownloadFtpFile"), so plain substring
# containment is more reliable here than a \b-anchored regex.
CATEGORIES = {
    "ftp": {
        "dirs": ["LinnworksMacroHelpers/Classes/Ftp"],
        "include": ["ftp"],
        "exclude": ["sftp", "ftps"],
        "title": "FTP",
    },
    "ftps": {
        "dirs": ["LinnworksMacroHelpers/Classes/Ftps"],
        "include": ["ftps"],
        "exclude": [],
        "title": "FTPS",
    },
    "sftp": {
        "dirs": ["LinnworksMacroHelpers/Classes/Sftp"],
        "include": ["sftp"],
        "exclude": [],
        "title": "SFTP",
    },
    "email": {
        "dirs": ["LinnworksMacroHelpers/Classes/Email"],
        "include": ["email"],
        "exclude": [],
        "title": "Email / SMTP",
    },
    "dropbox": {
        "dirs": ["LinnworksMacroHelpers/Classes/Dropbox"],
        "include": ["dropbox"],
        "exclude": [],
        "title": "Dropbox",
    },
    "web": {
        "dirs": [],
        "files": [
            "LinnworksMacroHelpers/Classes/ProxiedWebRequest.cs",
            "LinnworksMacroHelpers/Classes/ProxiedWebResponse.cs",
        ],
        "include": ["webrequest"],
        "exclude": [],
        "title": "Raw HTTP (ProxiedWebRequest)",
    },
}

# Where usage call sites are pulled from - the concrete IProxyFactory implementation.
USAGE_SOURCE_FILES = ["LinnMacroCustomer/FTPProxyFactory.cs"]
CONTRACT_FILE = "LinnworksMacroHelpers/Interfaces/IProxyHelper.cs"

DOC_COMMENT_RE = re.compile(r"^\s*///\s?(.*)$")
CLASS_RE = re.compile(
    r"public\s+(?:sealed\s+|abstract\s+|static\s+)*class\s+(\w+)\b[^\{]*\{"
)
PROPERTY_RE = re.compile(
    r"public\s+(?:override\s+|virtual\s+|static\s+)*"
    r"(?P<type>[\w<>\[\],\.\? ]+?)\s+(?P<name>\w+)\s*"
    r"(?:=>\s*[^;]+;|\{\s*get;[^\}]*\})"
)
METHOD_RE = re.compile(
    r"public\s+(?:override\s+|virtual\s+|async\s+|static\s+)*"
    r"(?P<ret>[\w<>\[\],\.\? ]+?)\s+(?P<name>\w+)\s*"
    r"\((?P<params>[^)]*)\)\s*\{"
)


def generated_banner():
    return (
        "<!-- GENERATED by scripts/sync_macro_integrations.py. "
        "Do not hand-edit - edit the source .cs file and re-run the script. -->\n"
    )


def read(path: pathlib.Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def leading_doc_comment(lines, decl_line_idx) -> str:
    """Collect the /// summary immediately above a declaration line."""
    doc_lines = []
    i = decl_line_idx - 1
    while i >= 0:
        m = DOC_COMMENT_RE.match(lines[i])
        if not m:
            break
        doc_lines.insert(0, m.group(1))
        i -= 1
    text = " ".join(doc_lines)
    text = re.sub(r"</?summary>", "", text).strip()
    return text


def find_matching_brace(text: str, open_brace_idx: int) -> int:
    depth = 0
    for i in range(open_brace_idx, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return i
    return len(text) - 1


def extract_classes(text: str):
    """Yield (name, doc_summary, body_text) for each public class in a file."""
    lines = text.splitlines()
    offsets = [0]
    for line in lines:
        offsets.append(offsets[-1] + len(line) + 1)

    for m in CLASS_RE.finditer(text):
        char_idx = m.start()
        line_idx = next(i for i, off in enumerate(offsets) if off > char_idx) - 1
        doc = leading_doc_comment(lines, line_idx)
        open_brace = text.index("{", m.end() - 1)
        close_brace = find_matching_brace(text, open_brace)
        body = text[open_brace + 1 : close_brace]
        yield m.group(1), doc, body


def extract_properties(body: str):
    for m in PROPERTY_RE.finditer(body):
        yield m.group("type").strip(), m.group("name").strip()


def name_matches(name: str, include: list, exclude: list) -> bool:
    lname = name.lower()
    if not any(term in lname for term in include):
        return False
    if any(term in lname for term in exclude):
        return False
    return True


def extract_methods_with_body(text: str, include: list, exclude: list):
    """Find public methods anywhere in `text` whose name matches, returning
    (signature, full_method_text)."""
    results = []
    for m in METHOD_RE.finditer(text):
        name = m.group("name")
        if not name_matches(name, include, exclude):
            continue
        open_brace = text.index("{", m.end() - 1)
        close_brace = find_matching_brace(text, open_brace)
        full = text[m.start() : close_brace + 1]
        sig = f"{m.group('ret').strip()} {name}({m.group('params').strip()})"
        results.append((sig, full))
    return results


def gather_type_docs(old_repo: pathlib.Path, cfg: dict):
    sections = []
    src_files = []
    for d in cfg.get("dirs", []):
        p = old_repo / d
        if p.exists():
            src_files.extend(sorted(p.glob("*.cs")))
    for f in cfg.get("files", []):
        p = old_repo / f
        if p.exists():
            src_files.append(p)

    for src in src_files:
        text = read(src)
        for cls_name, doc, body in extract_classes(text):
            props = list(extract_properties(body))
            sections.append(
                {
                    "class": cls_name,
                    "doc": doc,
                    "props": props,
                    "source": src.relative_to(old_repo).as_posix(),
                }
            )
    return sections, src_files


def gather_usage(old_repo: pathlib.Path, include: list, exclude: list):
    usages = []
    for rel in USAGE_SOURCE_FILES:
        p = old_repo / rel
        if not p.exists():
            continue
        text = read(p)
        for sig, body in extract_methods_with_body(text, include, exclude):
            usages.append({"sig": sig, "body": body, "source": rel})
    return usages


def gather_contract(old_repo: pathlib.Path, include: list, exclude: list):
    p = old_repo / CONTRACT_FILE
    if not p.exists():
        return []
    text = read(p)
    lines = []
    for line in text.splitlines():
        stripped = line.strip()
        if not (stripped.endswith(";") and "(" in stripped):
            continue
        # method name is the token right before '(' in an interface declaration
        m = re.search(r"(\w+)\s*\(", stripped)
        if m and name_matches(m.group(1), include, exclude):
            lines.append(stripped)
    return lines


def render_markdown(cfg: dict, type_sections, usages, contract_lines, src_files, old_repo):
    out = [generated_banner()]
    out.append(f"# {cfg['title']}\n")
    source_list = ", ".join(f"`{s.relative_to(old_repo).as_posix()}`" for s in src_files)
    out.append(f"Generated from: {source_list}\n\n_Last synced: {datetime.date.today().isoformat()}_\n")

    if contract_lines:
        out.append("## Contract (IProxyHelper.cs)\n")
        out.append("```csharp")
        out.extend(contract_lines)
        out.append("```\n")

    if type_sections:
        out.append("## Types\n")
        for s in type_sections:
            out.append(f"### `{s['class']}`  \n_source: `{s['source']}`_\n")
            if s["doc"]:
                out.append(s["doc"] + "\n")
            if s["props"]:
                out.append("| Property | Type |")
                out.append("|---|---|")
                for ptype, pname in s["props"]:
                    out.append(f"| `{pname}` | `{ptype}` |")
                out.append("")

    if usages:
        out.append("## Usage (from LinnMacroCustomer/FTPProxyFactory.cs)\n")
        out.append(
            "Real call-site implementation macros go through via `IProxyFactory`. "
            "Copy the pattern below rather than re-deriving it.\n"
        )
        for u in usages:
            out.append(f"### `{u['sig']}`\n")
            out.append("```csharp")
            out.append(u["body"])
            out.append("```\n")

    return "\n".join(out)


def sync_category(old_repo: pathlib.Path, key: str, cfg: dict):
    type_sections, src_files = gather_type_docs(old_repo, cfg)
    usages = gather_usage(old_repo, cfg["include"], cfg["exclude"])
    contract_lines = gather_contract(old_repo, cfg["include"], cfg["exclude"])

    md = render_markdown(cfg, type_sections, usages, contract_lines, src_files, old_repo)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    out_path = OUTPUT_DIR / f"{key}.md"
    out_path.write_text(md, encoding="utf-8")
    return out_path, len(type_sections), len(usages)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--old-repo", default=str(DEFAULT_OLD_REPO))
    parser.add_argument("--category", choices=sorted(CATEGORIES.keys()), default=None)
    args = parser.parse_args()

    old_repo = pathlib.Path(args.old_repo)
    if not old_repo.exists():
        print(f"Old repo not found at {old_repo}", file=sys.stderr)
        sys.exit(1)

    targets = [args.category] if args.category else sorted(CATEGORIES.keys())
    for key in targets:
        cfg = CATEGORIES[key]
        out_path, n_types, n_usages = sync_category(old_repo, key, cfg)
        rel = out_path.relative_to(PLATFORM_ROOT)
        print(f"{key:8s} -> {rel}  ({n_types} type(s), {n_usages} usage method(s))")


if __name__ == "__main__":
    main()
